use crate::model::*;

fn expr_source(e: &Expr) -> String {
    match e {
        Expr::Num(v) => {
            if *v >= 0x1000 {
                format!("0x{v:04X}")
            } else {
                v.to_string()
            }
        }
        Expr::Var(n) => n.clone(),
        Expr::Str(x) => format!("\"{}\"", x.escape_default()),
        Expr::SizeOfName(n) => format!("sizeof({n})"),
        Expr::AddrOf(n) => format!("&{n}"),
        Expr::Call(n, a) => format!(
            "{}({})",
            n,
            a.iter().map(expr_source).collect::<Vec<_>>().join(", ")
        ),
        Expr::Unary(op, a) => match op {
            UnOp::Neg => format!("-({})", expr_source(a)),
            UnOp::Not => format!("~({})", expr_source(a)),
            UnOp::LogicalNot => format!("!({})", expr_source(a)),
            UnOp::Inc1 => format!("({} + 1)", expr_source(a)),
            UnOp::Dec1 => format!("({} - 1)", expr_source(a)),
            UnOp::Shl1 => format!("({} << 1)", expr_source(a)),
            UnOp::Shr1 => format!("({} >> 1)", expr_source(a)),
        },
        Expr::Binary(op, a, b) => {
            let s = match op {
                BinOp::LogicalOr => "||",
                BinOp::LogicalAnd => "&&",
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::And => "&",
                BinOp::Or => "|",
                BinOp::Xor => "^",
                BinOp::Shl => "<<",
                BinOp::Shr => ">>",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Gt => ">",
                BinOp::Le => "<=",
                BinOp::Ge => ">=",
            };
            format!("({} {} {})", expr_source(a), s, expr_source(b))
        }
    }
}
fn format_readable(raw: &str) -> String {
    let mut o = String::new();
    for l in raw.lines() {
        let t = l.trim();
        if t.is_empty() {
            o.push('\n')
        } else if t.ends_with(':') || t.starts_with('.') || t.starts_with(';') {
            o.push_str(t);
            o.push('\n')
        } else {
            o.push_str("    ");
            o.push_str(t);
            o.push('\n')
        }
    }
    o
}

pub fn emit(p: &Program, l: &Layout, opt: OptLevel) -> Result<String, String> {
    let mut e = E {
        out: String::new(),
        n: 0,
        layout: l,
        program: p,
        fun: String::new(),
        loops: Vec::new(),
    };
    e.comment("Generated by SVM-C for the accumulator-machine target.");
    e.comment(&format!("Optimization: {:?}", opt));
    e.comment("Readable assembly: A is the accumulator, X is index/secondary operand.");
    e.blank();
    e.line(".load 0x0100");
    e.line(".entry __start");
    e.blank();
    e.line(".proc __start");
    e.comment("program initialization");
    for g in &p.globals {
        if let Some(Expr::Num(v)) = &g.init {
            e.line(&format!("LDAI {v}"));
            e.store(&VarInfo {
                ty: g.ty,
                addr: l.globals[&g.name].addr,
                len: 1,
            })
        }
    }
    e.blank();
    e.comment("enter user program");
    e.line("CALL main");
    e.line("HALT");
    e.line(".endproc");
    for f in &p.functions {
        e.function(f)?
    }
    Ok(format_readable(&e.out))
}
struct E<'a> {
    out: String,
    n: usize,
    layout: &'a Layout,
    program: &'a Program,
    fun: String,
    loops: Vec<(String, String)>,
}
impl<'a> E<'a> {
    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n')
    }
    fn blank(&mut self) {
        if !self.out.ends_with("\n\n") {
            self.out.push('\n')
        }
    }
    fn comment(&mut self, s: &str) {
        self.line(&format!("; {s}"))
    }
    fn label(&mut self, p: &str) -> String {
        let s = format!("__{}_{}_{}", self.fun, p, self.n);
        self.n += 1;
        s
    }
    fn var(&self, n: &str) -> Result<VarInfo, String> {
        self.layout
            .var(&self.fun, n)
            .cloned()
            .ok_or_else(|| format!("unknown variable '{n}' in {}", self.fun))
    }
    fn function(&mut self, f: &Function) -> Result<(), String> {
        self.fun = f.name.clone();
        self.loops.clear();
        self.blank();
        self.comment(&format!("function {}", f.name));
        self.line(&format!(".proc {}", f.name));
        for a in &f.params {
            let v = self.var(&a.name)?;
            self.comment(&format!(
                "parameter {} at 0x{:04X} (caller stores it)",
                a.name, v.addr
            ));
        }
        self.stmt(&f.body)?;
        if f.ret == Ty::Void {
            self.line("RET")
        } else {
            self.line("LDAI 0");
            self.line("RET")
        }
        self.line(".endproc");
        Ok(())
    }
    fn load(&mut self, v: &VarInfo) {
        if v.addr <= 0x00FF {
            self.line(&format!(
                "LDA{}Z 0x{:02X}",
                if v.ty.size() == 1 { "8" } else { "16" },
                v.addr
            ))
        } else {
            self.line(&format!(
                "LDA{} 0x{:04X}",
                if v.ty.size() == 1 { "8" } else { "16" },
                v.addr
            ))
        }
    }
    fn store(&mut self, v: &VarInfo) {
        if v.addr <= 0x00FF {
            self.line(&format!(
                "STA{}Z 0x{:02X}",
                if v.ty.size() == 1 { "8" } else { "16" },
                v.addr
            ))
        } else {
            self.line(&format!(
                "STA{} 0x{:04X}",
                if v.ty.size() == 1 { "8" } else { "16" },
                v.addr
            ))
        }
    }
    fn stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match s {
            Stmt::Block(v) => {
                for x in v {
                    self.stmt(x)?
                }
            }
            Stmt::Var(v) => {
                if let Some(x) = &v.init {
                    self.comment(&format!(
                        "{} {} = {};",
                        if v.ty.size() == 1 { "u8" } else { "u16" },
                        v.name,
                        expr_source(x)
                    ));
                    self.expr(x)?;
                    let z = self.var(&v.name)?;
                    self.store(&z)
                }
            }
            Stmt::Assign(n, x) => {
                self.comment(&format!("{} = {};", n, expr_source(x)));
                self.expr(x)?;
                let v = self.var(n)?;
                self.store(&v)
            }
            Stmt::Expr(x) => {
                self.comment(&format!("{};", expr_source(x)));
                self.expr(x)?
            }
            Stmt::If(c, a, b) => {
                self.comment(&format!("if ({})", expr_source(c)));
                let els = self.label("else");
                let end = self.label("ifend");
                self.expr(c)?;
                self.line("CMPI 0");
                self.line(&format!("JZ {els}"));
                self.stmt(a)?;
                self.line(&format!("JMP {end}"));
                self.line(&format!("{els}:"));
                if let Some(b) = b {
                    self.stmt(b)?
                }
                self.line(&format!("{end}:"))
            }
            Stmt::While(c, b) => {
                self.comment(&format!("while ({})", expr_source(c)));
                let top = self.label("while");
                let end = self.label("wend");
                self.line(&format!("{top}:"));
                self.expr(c)?;
                self.line("CMPI 0");
                self.line(&format!("JZ {end}"));
                self.loops.push((top.clone(), end.clone()));
                self.stmt(b)?;
                self.loops.pop();
                self.line(&format!("JMP {top}"));
                self.line(&format!("{end}:"))
            }
            Stmt::DoWhile(b, c) => {
                let top = self.label("do");
                let cond = self.label("docond");
                let end = self.label("doend");
                self.line(&format!("{top}:"));
                self.loops.push((cond.clone(), end.clone()));
                self.stmt(b)?;
                self.loops.pop();
                self.line(&format!("{cond}:"));
                self.expr(c)?;
                self.line("CMPI 0");
                self.line(&format!("JNZ {top}"));
                self.line(&format!("{end}:"))
            }
            Stmt::Break => {
                let (_, b) = self.loops.last().ok_or("break outside loop")?.clone();
                self.line(&format!("JMP {b}"))
            }
            Stmt::Continue => {
                let (c, _) = self.loops.last().ok_or("continue outside loop")?.clone();
                self.line(&format!("JMP {c}"))
            }
            Stmt::For(i, c, st, b) => {
                self.comment("for loop");
                if let Some(i) = i {
                    self.stmt(i)?
                }
                let top = self.label("for");
                let step = self.label("fstep");
                let end = self.label("fend");
                self.line(&format!("{top}:"));
                if let Some(c) = c {
                    self.expr(c)?;
                    self.line("CMPI 0");
                    self.line(&format!("JZ {end}"))
                }
                self.loops.push((step.clone(), end.clone()));
                self.stmt(b)?;
                self.loops.pop();
                self.line(&format!("{step}:"));
                if let Some(st) = st {
                    self.stmt(st)?
                }
                self.line(&format!("JMP {top}"));
                self.line(&format!("{end}:"))
            }
            Stmt::Return(x) => {
                if let Some(x) = x {
                    self.comment(&format!("return {};", expr_source(x)));
                    self.expr(x)?
                } else {
                    self.comment("return;")
                }
                self.line("RET")
            }
            Stmt::Empty => {}
        }
        Ok(())
    }
    fn expr(&mut self, x: &Expr) -> Result<(), String> {
        match x {
            Expr::Num(v) => self.line(&format!("LDAI {v}")),
            Expr::Var(n) => {
                let v = self.var(n)?;
                self.load(&v)
            }
            Expr::Unary(op, a) => {
                self.expr(a)?;
                match op {
                    UnOp::Neg => self.line("NEG"),
                    UnOp::Not => self.line("NOT"),
                    UnOp::Inc1 => self.line("INC"),
                    UnOp::Dec1 => self.line("DEC"),
                    UnOp::Shl1 => self.line("SHL1"),
                    UnOp::Shr1 => self.line("SHR1"),
                    UnOp::LogicalNot => {
                        let t = self.label("not_t");
                        let e = self.label("not_e");
                        self.line("CMPI 0");
                        self.line(&format!("JZ {t}"));
                        self.line("LDAI 0");
                        self.line(&format!("JMP {e}"));
                        self.line(&format!("{t}:"));
                        self.line("LDAI 1");
                        self.line(&format!("{e}:"))
                    }
                }
            }
            Expr::Binary(op, a, b) => {
                if matches!(op, BinOp::LogicalAnd | BinOp::LogicalOr) {
                    let short = self.label("logic_short");
                    let end = self.label("logic_end");
                    self.expr(a)?;
                    self.line("CMPI 0");
                    match op {
                        BinOp::LogicalAnd => self.line(&format!("JZ {short}")),
                        BinOp::LogicalOr => self.line(&format!("JNZ {short}")),
                        _ => unreachable!(),
                    }
                    self.expr(b)?;
                    self.line("CMPI 0");
                    let truth = self.label("logic_truth");
                    self.line(&format!("JNZ {truth}"));
                    self.line("LDAI 0");
                    self.line(&format!("JMP {end}"));
                    self.line(&format!("{truth}:"));
                    self.line("LDAI 1");
                    self.line(&format!("JMP {end}"));
                    self.line(&format!("{short}:"));
                    self.line(match op {
                        BinOp::LogicalAnd => "LDAI 0",
                        BinOp::LogicalOr => "LDAI 1",
                        _ => unreachable!(),
                    });
                    self.line(&format!("{end}:"));
                    return Ok(());
                }
                self.expr(a)?;
                self.line("PUSHA");
                self.expr(b)?;
                self.line("TAX");
                self.line("POPA");
                match op {
                    BinOp::Add => self.line("ADDX"),
                    BinOp::Sub => self.line("SUBX"),
                    BinOp::Mul => self.line("MULX"),
                    BinOp::Div => self.line("DIVX"),
                    BinOp::Mod => self.line("MODX"),
                    BinOp::And => self.line("ANDX"),
                    BinOp::Or => self.line("ORX"),
                    BinOp::Xor => self.line("XORX"),
                    BinOp::Shl => self.line("SHLX"),
                    BinOp::Shr => self.line("SHRX"),
                    BinOp::LogicalAnd | BinOp::LogicalOr => unreachable!(),
                    _ => self.cmp_bool(*op)?,
                }
            }
            Expr::Str(_) => return Err("string literal is only valid in puts()".into()),
            Expr::SizeOfName(_) => return Err("internal: sizeof was not lowered".into()),
            Expr::AddrOf(_) => return Err("internal: address-of was not lowered".into()),
            Expr::Call(n, a) => self.call(n, a)?,
        }
        Ok(())
    }
    fn cmp_bool(&mut self, op: BinOp) -> Result<(), String> {
        let t = self.label("cmp_t");
        let f = self.label("cmp_f");
        let e = self.label("cmp_e");
        self.line("CMPX");
        match op {
            BinOp::Eq => self.line(&format!("JZ {t}")),
            BinOp::Ne => self.line(&format!("JNZ {t}")),
            BinOp::Lt => self.line(&format!("JNC {t}")),
            BinOp::Ge => self.line(&format!("JC {t}")),
            BinOp::Le => {
                self.line(&format!("JNC {t}"));
                self.line(&format!("JZ {t}"))
            }
            BinOp::Gt => {
                self.line(&format!("JNC {f}"));
                self.line(&format!("JZ {f}"));
                self.line(&format!("JMP {t}"))
            }
            _ => return Err("internal comparison error".into()),
        }
        self.line(&format!("{f}:"));
        self.line("LDAI 0");
        self.line(&format!("JMP {e}"));
        self.line(&format!("{t}:"));
        self.line("LDAI 1");
        self.line(&format!("{e}:"));
        Ok(())
    }
    fn emit_console_getc_inline(&mut self) {
        let wait = self.label("console_wait");
        self.line(&format!("{}:", wait));
        self.line("LDA8 0xFF21");
        self.line("ANDI 1");
        self.line(&format!("JZ {}", wait));
        self.line("LDA8 0xFF20");
        self.line("PUSHA");
        self.line("LDAI 1");
        self.line("STA8 0xFF21");
        self.line("POPA");
    }

    fn call(&mut self, n: &str, a: &[Expr]) -> Result<(), String> {
        match n {
            "puts" => {
                if a.len() != 1 {
                    return Err("puts expects 1 string literal".into());
                }
                let Expr::Str(text) = &a[0] else {
                    return Err("puts expects a string literal".into());
                };
                for ch in text.bytes().chain([13u8, 10u8]) {
                    self.line(&format!("LDAI {}", ch));
                    self.line("STA8 0xFF20")
                }
                self.line("LDAI 0");
                return Ok(());
            }
            "putc" => {
                if a.len() != 1 {
                    return Err("putc expects 1 argument".into());
                }
                self.expr(&a[0])?;
                self.line("STA8 0xFF20");
                self.line("LDAI 0");
                return Ok(());
            }
            "getc" => {
                if !a.is_empty() {
                    return Err("getc expects 0 arguments".into());
                }
                self.emit_console_getc_inline();
                return Ok(());
            }
            "clock_lo" => {
                if !a.is_empty() {
                    return Err("clock_lo expects 0 arguments".into());
                }
                self.line("LDA16 0xFF1A");
                return Ok(());
            }
            "clock_hi" => {
                if !a.is_empty() {
                    return Err("clock_hi expects 0 arguments".into());
                }
                self.line("LDA16 0xFF1C");
                return Ok(());
            }
            "instr_lo" => {
                if !a.is_empty() {
                    return Err("instr_lo expects 0 arguments".into());
                }
                self.line("LDA16 0xFF22");
                return Ok(());
            }
            "instr_hi" => {
                if !a.is_empty() {
                    return Err("instr_hi expects 0 arguments".into());
                }
                self.line("LDA16 0xFF24");
                return Ok(());
            }
            "asr1" => {
                if a.len() != 1 {
                    return Err("asr1 expects 1 argument".into());
                }
                self.expr(&a[0])?;
                self.line("ASR1");
                return Ok(());
            }
            "mul_q15" => {
                if a.len() != 2 {
                    return Err("mul_q15 expects 2 arguments".into());
                }
                self.expr(&a[0])?;
                self.line("PUSHA");
                self.expr(&a[1])?;
                self.line("TAX");
                self.line("POPA");
                self.line("MULQ15X");
                return Ok(());
            }
            "vload8" | "vload16" => {
                if a.len() != 1 {
                    return Err(format!("{n} expects 1 argument"));
                }
                self.expr(&a[0])?;
                self.line("TAX");
                self.line(if n == "vload8" {
                    "VLDA8 [X]"
                } else {
                    "VLDA16 [X]"
                });
                return Ok(());
            }
            "vstore8" | "vstore16" => {
                if a.len() != 2 {
                    return Err(format!("{n} expects 2 arguments"));
                }
                self.expr(&a[1])?;
                self.line("PUSHA");
                self.expr(&a[0])?;
                self.line("TAX");
                self.line("POPA");
                self.line(if n == "vstore8" {
                    "VSTA8 [X]"
                } else {
                    "VSTA16 [X]"
                });
                self.line("LDAI 0");
                return Ok(());
            }
            "load8" | "load16" => {
                if a.len() != 1 {
                    return Err(format!("{n} expects 1 argument"));
                }
                if let Expr::Num(addr) = &a[0] {
                    if *addr <= 0x00FF {
                        self.line(&format!(
                            "LDA{}Z 0x{:02X}",
                            if n == "load8" { "8" } else { "16" },
                            *addr
                        ));
                    } else {
                        self.line(&format!(
                            "LDA{} 0x{:04X}",
                            if n == "load8" { "8" } else { "16" },
                            *addr
                        ));
                    }
                } else {
                    self.expr(&a[0])?;
                    self.line("TAX");
                    self.line(if n == "load8" {
                        "LDA8 [X]"
                    } else {
                        "LDA16 [X]"
                    });
                }
                return Ok(());
            }
            "store8" | "store16" => {
                if a.len() != 2 {
                    return Err(format!("{n} expects 2 arguments"));
                }
                if let Expr::Num(addr) = &a[0] {
                    self.expr(&a[1])?;
                    if *addr <= 0x00FF {
                        self.line(&format!(
                            "STA{}Z 0x{:02X}",
                            if n == "store8" { "8" } else { "16" },
                            *addr
                        ));
                    } else {
                        self.line(&format!(
                            "STA{} 0x{:04X}",
                            if n == "store8" { "8" } else { "16" },
                            *addr
                        ));
                    }
                } else {
                    self.expr(&a[1])?;
                    self.line("PUSHA");
                    self.expr(&a[0])?;
                    self.line("TAX");
                    self.line("POPA");
                    self.line(if n == "store8" {
                        "STA8 [X]"
                    } else {
                        "STA16 [X]"
                    });
                }
                self.line("LDAI 0");
                return Ok(());
            }
            _ => {}
        }
        let sig = self
            .layout
            .funcs
            .get(n)
            .ok_or_else(|| format!("unknown function '{n}'"))?;
        if sig.params.len() != a.len() {
            return Err(format!(
                "function '{n}' expects {} arguments",
                sig.params.len()
            ));
        }
        let f = self
            .program
            .functions
            .iter()
            .find(|f| f.name == n)
            .cloned()
            .ok_or_else(|| format!("unknown function '{n}'"))?;
        for arg in a {
            self.expr(arg)?;
            self.line("PUSHA");
        }
        for param in f.params.iter().rev() {
            self.line("POPA");
            let v = self
                .layout
                .var(n, &param.name)
                .cloned()
                .ok_or_else(|| format!("missing parameter layout for {n}.{}", param.name))?;
            if v.addr <= 0x00FF {
                self.line(&format!(
                    "STA{}Z 0x{:02X}",
                    if v.ty.size() == 1 { "8" } else { "16" },
                    v.addr
                ));
            } else {
                self.line(&format!(
                    "STA{} 0x{:04X}",
                    if v.ty.size() == 1 { "8" } else { "16" },
                    v.addr
                ));
            }
        }
        self.line(&format!("CALL {n}"));
        Ok(())
    }
}
