use crate::{backend_register, model::*};
fn slot(r: &str) -> Result<u16, String> {
    let u = r.trim().to_ascii_uppercase();
    let n = u
        .strip_prefix('R')
        .ok_or_else(|| format!("expected virtual register, got {r}"))?
        .parse::<u16>()
        .map_err(|_| format!("bad virtual register {r}"))?;
    if n > 7 {
        return Err(format!("virtual register out of range: {r}"));
    }
    Ok(n * 2)
}
fn ops(s: &str) -> Vec<String> {
    s.split(',')
        .map(|x| x.trim().to_string())
        .filter(|x| !x.is_empty())
        .collect()
}
fn ptr_reg(s: &str) -> Result<String, String> {
    let t = s.trim();
    if !(t.starts_with('[') && t.ends_with(']')) {
        return Err(format!("expected [Rn], got {s}"));
    }
    Ok(t[1..t.len() - 1]
        .trim()
        .trim_end_matches('+')
        .trim_start_matches('-')
        .trim()
        .to_string())
}
fn emit_load(out: &mut String, r: &str) -> Result<(), String> {
    out.push_str(&format!("    ZLD16 0x{:02X}\n", slot(r)?));
    Ok(())
}
fn emit_store(out: &mut String, r: &str) -> Result<(), String> {
    out.push_str(&format!("    ZST16 0x{:02X}, b0\n", slot(r)?));
    Ok(())
}
fn binary(out: &mut String, m: &str, d: &str, s: &str) -> Result<(), String> {
    emit_load(out, d)?;
    emit_load(out, s)?;
    out.push_str(&format!("    {m} b1,b0\n"));
    emit_store(out, d)
}
fn immediate(out: &mut String, m: &str, d: &str, v: &str) -> Result<(), String> {
    emit_load(out, d)?;
    out.push_str(&format!("    LDI {v}\n    {m} b1,b0\n"));
    emit_store(out, d)
}
fn translate(register_asm: &str) -> Result<String, String> {
    let mut out = String::from("; Generated by SVM-C for the Belt16 target.\n");
    for raw in register_asm.lines() {
        let t = raw.trim();
        if t.is_empty() {
            out.push('\n');
            continue;
        }
        if t.starts_with(';') {
            continue;
        }
        if t.starts_with('.') || t.ends_with(':') {
            out.push_str(t);
            out.push('\n');
            continue;
        }
        let mut p = t.splitn(2, char::is_whitespace);
        let m = p.next().unwrap_or("").to_ascii_uppercase();
        let a = ops(p.next().unwrap_or(""));
        match m.as_str() {
            "NOP" | "HALT" | "RET" | "EI" | "DI" | "IRET" => out.push_str(&format!("    {m}\n")),
            "JMP" | "JZ" | "JNZ" | "JC" | "JNC" | "JN" | "JNN" | "CALL" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                out.push_str(&format!("    {m} {}\n", a[0]))
            }
            "MOVI" => {
                if a.len() != 2 {
                    return Err("bad MOVI".into());
                }
                out.push_str(&format!("    LDI {}\n", a[1]));
                emit_store(&mut out, &a[0])?
            }
            "MOV" => {
                if a.len() != 2 {
                    return Err("bad MOV".into());
                }
                emit_load(&mut out, &a[1])?;
                emit_store(&mut out, &a[0])?
            }
            "ADD" | "SUB" | "AND" | "OR" | "XOR" | "MUL" | "DIV" | "MOD" | "SHL" | "SHR"
            | "CMP" | "ADC" | "SBC" | "MULHU" | "MULQ15" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                binary(&mut out, &m, &a[0], &a[1])?
            }
            "ADDI" | "SUBI" | "ANDI" | "ORI" | "XORI" | "CMPI" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let op = match m.as_str() {
                    "ADDI" => "ADD",
                    "SUBI" => "SUB",
                    "ANDI" => "AND",
                    "ORI" => "OR",
                    "XORI" => "XOR",
                    _ => "CMP",
                };
                immediate(&mut out, op, &a[0], &a[1])?
            }
            "NOT" | "NEG" | "ASR1" | "SHL1" | "SHR1" | "RCR1" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                emit_load(&mut out, &a[0])?;
                out.push_str(&format!("    {m} b0\n"));
                emit_store(&mut out, &a[0])?
            }
            "INC" | "DEC" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                immediate(&mut out, if m == "INC" { "ADD" } else { "SUB" }, &a[0], "1")?
            }
            "PUSH" => {
                if a.len() != 1 {
                    return Err("bad PUSH".into());
                }
                emit_load(&mut out, &a[0])?;
                out.push_str("    PUSH b0\n")
            }
            "POP" => {
                if a.len() != 1 {
                    return Err("bad POP".into());
                }
                out.push_str("    POP\n");
                emit_store(&mut out, &a[0])?
            }
            "ZLOAD8" | "ZLOAD16" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                out.push_str(&format!(
                    "    {} {}\n",
                    if m == "ZLOAD8" { "ZLD8" } else { "ZLD16" },
                    a[0]
                ));
                emit_store(&mut out, "R0")?
            }
            "ZSTORE8" | "ZSTORE16" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                emit_load(&mut out, "R0")?;
                out.push_str(&format!(
                    "    {} {}, b0\n",
                    if m == "ZSTORE8" { "ZST8" } else { "ZST16" },
                    a[0]
                ))
            }
            "LOAD8" | "LOAD16" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let pr = ptr_reg(&a[1])?;
                emit_load(&mut out, &pr)?;
                out.push_str(&format!(
                    "    {} [b0]\n",
                    if m == "LOAD8" { "LD8" } else { "LD16" }
                ));
                emit_store(&mut out, &a[0])?
            }
            "STORE8" | "STORE16" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let pr = ptr_reg(&a[0])?;
                emit_load(&mut out, &pr)?;
                emit_load(&mut out, &a[1])?;
                out.push_str(&format!(
                    "    {} [b1], b0\n",
                    if m == "STORE8" { "ST8" } else { "ST16" }
                ))
            }
            "VLOAD8" | "VLOAD16" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let pr = ptr_reg(&a[1])?;
                emit_load(&mut out, &pr)?;
                out.push_str(&format!(
                    "    {} [b0]\n",
                    if m == "VLOAD8" { "VLD8" } else { "VLD16" }
                ));
                emit_store(&mut out, &a[0])?
            }
            "VSTORE8" | "VSTORE16" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let pr = ptr_reg(&a[0])?;
                emit_load(&mut out, &pr)?;
                emit_load(&mut out, &a[1])?;
                out.push_str(&format!(
                    "    {} [b1], b0\n",
                    if m == "VSTORE8" { "VST8" } else { "VST16" }
                ))
            }
            _ => return Err(format!("Belt lowering does not know instruction: {t}")),
        }
    }
    Ok(out)
}
pub fn emit(p: &Program, l: &Layout, opt: OptLevel) -> Result<String, String> {
    translate(&backend_register::emit(p, l, opt)?)
}
