use crate::model::*;
fn es(e: &Expr) -> String {
    match e {
        Expr::Num(v) => {
            if *v >= 0x1000 {
                format!("0x{v:04X}")
            } else {
                v.to_string()
            }
        }
        Expr::Var(n) => n.clone(),
        Expr::Str(x) => format!("\"{}\"", x.escape_default()),
        Expr::SizeOfName(n) => format!("sizeof({n})"),
        Expr::AddrOf(n) => format!("&{n}"),
        Expr::Call(n, a) => format!("{}({})", n, a.iter().map(es).collect::<Vec<_>>().join(", ")),
        Expr::Unary(o, a) => {
            let x = es(a);
            match o {
                UnOp::Neg => format!("-({x})"),
                UnOp::Not => format!("~({x})"),
                UnOp::LogicalNot => format!("!({x})"),
                UnOp::Inc1 => format!("({x} + 1)"),
                UnOp::Dec1 => format!("({x} - 1)"),
                UnOp::Shl1 => format!("({x} << 1)"),
                UnOp::Shr1 => format!("({x} >> 1)"),
            }
        }
        Expr::Binary(o, a, b) => {
            let q = match o {
                BinOp::LogicalOr => "||",
                BinOp::LogicalAnd => "&&",
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::And => "&",
                BinOp::Or => "|",
                BinOp::Xor => "^",
                BinOp::Shl => "<<",
                BinOp::Shr => ">>",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Gt => ">",
                BinOp::Le => "<=",
                BinOp::Ge => ">=",
            };
            format!("({} {q} {})", es(a), es(b))
        }
    }
}
fn pretty(r: &str) -> String {
    let mut o = String::new();
    for l in r.lines() {
        let t = l.trim();
        if t.is_empty() {
            o.push('\n')
        } else if t.ends_with(':') || t.starts_with('.') || t.starts_with(';') {
            o.push_str(t);
            o.push('\n')
        } else {
            o.push_str("    ");
            o.push_str(t);
            o.push('\n')
        }
    }
    o
}
pub fn emit(p: &Program, l: &Layout, opt: OptLevel) -> Result<String, String> {
    let mut e = E {
        out: String::new(),
        n: 0,
        l,
        prog: p,
        fun: String::new(),
        loops: Vec::new(),
    };
    e.c("Generated by SVM-C for the memory-register-machine target.");
    e.c(&format!("Optimization: {:?}", opt));
    e.c("Readable assembly: W is the working register; direct file operands use zero page.");
    e.c("Compiler scratch: 0x000E..0x000F is reserved for hot 16-bit expression temporaries.");
    e.blank();
    e.line(".load 0x0100");
    e.line(".entry __start");
    e.blank();
    e.line(".proc __start");
    for g in &p.globals {
        if let Some(Expr::Num(v)) = &g.init {
            e.line(&format!("LDI {v}"));
            e.store(&VarInfo {
                ty: g.ty,
                addr: l.globals[&g.name].addr,
                len: 1,
            })
        }
    }
    e.line("CALL main");
    e.line("HALT");
    e.line(".endproc");
    for f in &p.functions {
        e.fun(f)?
    }
    Ok(pretty(&e.out))
}
struct E<'a> {
    out: String,
    n: usize,
    l: &'a Layout,
    prog: &'a Program,
    fun: String,
    loops: Vec<(String, String)>,
}
impl<'a> E<'a> {
    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n')
    }
    fn blank(&mut self) {
        self.out.push('\n')
    }
    fn c(&mut self, s: &str) {
        self.line(&format!("; {s}"))
    }
    fn lab(&mut self, p: &str) -> String {
        let x = format!("__{}_{}_{}", self.fun, p, self.n);
        self.n += 1;
        x
    }
    fn var(&self, n: &str) -> Result<VarInfo, String> {
        self.l
            .var(&self.fun, n)
            .cloned()
            .ok_or_else(|| format!("unknown variable '{n}'"))
    }
    fn load(&mut self, v: &VarInfo) {
        let w = if v.ty.size() == 1 { "8" } else { "16" };
        if v.addr <= 0xff {
            self.line(&format!("MOV{w} 0x{:02X}, W", v.addr))
        } else {
            self.line(&format!("FSR0I 0x{:04X}", v.addr));
            self.line(if v.ty.size() == 1 { "LDB0" } else { "LDW0" })
        }
    }
    fn store(&mut self, v: &VarInfo) {
        let w = if v.ty.size() == 1 { "8" } else { "16" };
        if v.addr <= 0xff {
            self.line(&format!("MOV{w} W, 0x{:02X}", v.addr))
        } else {
            self.line(&format!("FSR0I 0x{:04X}", v.addr));
            self.line(if v.ty.size() == 1 { "STB0" } else { "STW0" })
        }
    }
    fn fun(&mut self, f: &Function) -> Result<(), String> {
        self.fun = f.name.clone();
        self.loops.clear();
        self.blank();
        self.c(&format!("function {}", f.name));
        self.line(&format!(".proc {}", f.name));
        for a in &f.params {
            let v = self.var(&a.name)?;
            self.c(&format!(
                "parameter {} at 0x{:04X} (caller stores it)",
                a.name, v.addr
            ));
        }
        self.stmt(&f.body)?;
        if f.ret == Ty::Void {
            self.line("RET")
        } else {
            self.line("LDI 0");
            self.line("RET")
        }
        self.line(".endproc");
        Ok(())
    }
    fn stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match s {
            Stmt::Block(v) => {
                for x in v {
                    self.stmt(x)?
                }
            }
            Stmt::Var(v) => {
                if let Some(x) = &v.init {
                    self.c(&format!(
                        "{} {} = {};",
                        if v.ty.size() == 1 { "u8" } else { "u16" },
                        v.name,
                        es(x)
                    ));
                    self.expr(x)?;
                    let z = self.var(&v.name)?;
                    self.store(&z)
                }
            }
            Stmt::Assign(n, x) => {
                self.c(&format!("{} = {};", n, es(x)));
                let v = self.var(n)?;
                let mut done = false;
                if v.ty == Ty::U16 && v.addr <= 0x00FF {
                    if let Expr::Binary(op, a, b) = x {
                        if matches!(&**a,Expr::Var(q) if q==n)
                            && matches!(
                                *op,
                                BinOp::Add | BinOp::Sub | BinOp::And | BinOp::Or | BinOp::Xor
                            )
                        {
                            self.expr(b)?;
                            let mn = match *op {
                                BinOp::Add => "ADD",
                                BinOp::Sub => "SUB",
                                BinOp::And => "AND",
                                BinOp::Or => "OR",
                                _ => "XOR",
                            };
                            self.line(&format!("{mn} 0x{:02X},F", v.addr));
                            done = true
                        }
                    }
                    if !done {
                        if let Expr::Unary(op, a) = x {
                            if matches!(&**a,Expr::Var(q) if q==n) {
                                if matches!(*op, UnOp::Inc1 | UnOp::Dec1) {
                                    self.line(&format!(
                                        "{} 0x{:02X}",
                                        if matches!(*op, UnOp::Inc1) {
                                            "INC"
                                        } else {
                                            "DEC"
                                        },
                                        v.addr
                                    ));
                                    done = true
                                }
                            }
                        }
                    }
                }
                if !done {
                    self.expr(x)?;
                    self.store(&v)
                }
            }
            Stmt::Expr(x) => {
                self.c(&format!("{};", es(x)));
                self.expr(x)?
            }
            Stmt::If(c, a, b) => {
                let el = self.lab("else");
                let en = self.lab("ifend");
                self.expr(c)?;
                self.line("CMPI 0");
                self.line(&format!("JZ {el}"));
                self.stmt(a)?;
                self.line(&format!("JMP {en}"));
                self.line(&format!("{el}:"));
                if let Some(x) = b {
                    self.stmt(x)?
                }
                self.line(&format!("{en}:"))
            }
            Stmt::While(c, b) => {
                let t = self.lab("while");
                let e = self.lab("wend");
                self.line(&format!("{t}:"));
                self.expr(c)?;
                self.line("CMPI 0");
                self.line(&format!("JZ {e}"));
                self.loops.push((t.clone(), e.clone()));
                self.stmt(b)?;
                self.loops.pop();
                self.line(&format!("JMP {t}"));
                self.line(&format!("{e}:"))
            }
            Stmt::DoWhile(b, c) => {
                let t = self.lab("do");
                let q = self.lab("docond");
                let e = self.lab("doend");
                self.line(&format!("{t}:"));
                self.loops.push((q.clone(), e.clone()));
                self.stmt(b)?;
                self.loops.pop();
                self.line(&format!("{q}:"));
                self.expr(c)?;
                self.line("CMPI 0");
                self.line(&format!("JNZ {t}"));
                self.line(&format!("{e}:"))
            }
            Stmt::Break => {
                let (_, b) = self.loops.last().ok_or("break outside loop")?.clone();
                self.line(&format!("JMP {b}"))
            }
            Stmt::Continue => {
                let (c, _) = self.loops.last().ok_or("continue outside loop")?.clone();
                self.line(&format!("JMP {c}"))
            }
            Stmt::For(i, c, st, b) => {
                if let Some(x) = i {
                    self.stmt(x)?
                }
                let t = self.lab("for");
                let q = self.lab("fstep");
                let e = self.lab("fend");
                self.line(&format!("{t}:"));
                if let Some(x) = c {
                    self.expr(x)?;
                    self.line("CMPI 0");
                    self.line(&format!("JZ {e}"))
                }
                self.loops.push((q.clone(), e.clone()));
                self.stmt(b)?;
                self.loops.pop();
                self.line(&format!("{q}:"));
                if let Some(x) = st {
                    self.stmt(x)?
                }
                self.line(&format!("JMP {t}"));
                self.line(&format!("{e}:"))
            }
            Stmt::Return(x) => {
                if let Some(x) = x {
                    self.expr(x)?
                }
                self.line("RET")
            }
            Stmt::Empty => {}
        }
        Ok(())
    }
    fn expr(&mut self, x: &Expr) -> Result<(), String> {
        match x {
            Expr::Num(v) => self.line(&format!("LDI {v}")),
            Expr::Var(n) => {
                let v = self.var(n)?;
                self.load(&v)
            }
            Expr::Unary(o, a) => {
                self.expr(a)?;
                self.line(match o {
                    UnOp::Neg => "NEGW",
                    UnOp::Not => "NOTW",
                    UnOp::Inc1 => "INCW",
                    UnOp::Dec1 => "DECW",
                    UnOp::Shl1 => "SHL1W",
                    UnOp::Shr1 => "SHR1W",
                    UnOp::LogicalNot => {
                        let t = self.lab("not_t");
                        let e = self.lab("not_e");
                        self.line("CMPI 0");
                        self.line(&format!("JZ {t}"));
                        self.line("LDI 0");
                        self.line(&format!("JMP {e}"));
                        self.line(&format!("{t}:"));
                        self.line("LDI 1");
                        self.line(&format!("{e}:"));
                        return Ok(());
                    }
                })
            }
            Expr::Binary(o, a, b) => {
                if matches!(o, BinOp::LogicalAnd | BinOp::LogicalOr) {
                    let short = self.lab("logic_short");
                    let end = self.lab("logic_end");
                    self.expr(a)?;
                    self.line("CMPI 0");
                    match o {
                        BinOp::LogicalAnd => self.line(&format!("JZ {short}")),
                        BinOp::LogicalOr => self.line(&format!("JNZ {short}")),
                        _ => unreachable!(),
                    }
                    self.expr(b)?;
                    self.line("CMPI 0");
                    let truth = self.lab("logic_truth");
                    self.line(&format!("JNZ {truth}"));
                    self.line("LDI 0");
                    self.line(&format!("JMP {end}"));
                    self.line(&format!("{truth}:"));
                    self.line("LDI 1");
                    self.line(&format!("JMP {end}"));
                    self.line(&format!("{short}:"));
                    self.line(match o {
                        BinOp::LogicalAnd => "LDI 0",
                        BinOp::LogicalOr => "LDI 1",
                        _ => unreachable!(),
                    });
                    self.line(&format!("{end}:"));
                    return Ok(());
                }
                // Native immediate W operations are cheaper than routing a literal
                // through the expression stack and compiler scratch cell.
                if let Expr::Num(v) = &**b {
                    match o {
                        BinOp::Add => {
                            self.expr(a)?;
                            self.line(&format!("ADDI {v}"));
                            return Ok(());
                        }
                        BinOp::Sub => {
                            self.expr(a)?;
                            self.line(&format!("SUBI {v}"));
                            return Ok(());
                        }
                        BinOp::And => {
                            self.expr(a)?;
                            self.line(&format!("ANDI {v}"));
                            return Ok(());
                        }
                        BinOp::Or => {
                            self.expr(a)?;
                            self.line(&format!("ORI {v}"));
                            return Ok(());
                        }
                        BinOp::Xor => {
                            self.expr(a)?;
                            self.line(&format!("XORI {v}"));
                            return Ok(());
                        }
                        BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Gt | BinOp::Le | BinOp::Ge => {
                            self.expr(a)?;
                            self.line(&format!("CMPI {v}"));
                            self.cmp_flags(*o)?;
                            return Ok(());
                        }
                        _ => {}
                    }
                }
                if let Expr::Num(v) = &**a {
                    match o {
                        BinOp::Add => {
                            self.expr(b)?;
                            self.line(&format!("ADDI {v}"));
                            return Ok(());
                        }
                        BinOp::And => {
                            self.expr(b)?;
                            self.line(&format!("ANDI {v}"));
                            return Ok(());
                        }
                        BinOp::Or => {
                            self.expr(b)?;
                            self.line(&format!("ORI {v}"));
                            return Ok(());
                        }
                        BinOp::Xor => {
                            self.expr(b)?;
                            self.line(&format!("XORI {v}"));
                            return Ok(());
                        }
                        _ => {}
                    }
                }
                self.expr(a)?;
                self.line("PUSHW");
                self.expr(b)?;
                self.line("MOV16 W, 0x0E");
                self.line("POPW");
                match o {
                    BinOp::Add => self.line("ADD 0x0E,W"),
                    BinOp::Sub => self.line("SUB 0x0E,W"),
                    BinOp::Mul => self.line("MUL 0x0E,W"),
                    BinOp::Div => self.line("DIV 0x0E,W"),
                    BinOp::Mod => self.line("MOD 0x0E,W"),
                    BinOp::And => self.line("AND 0x0E,W"),
                    BinOp::Or => self.line("OR 0x0E,W"),
                    BinOp::Xor => self.line("XOR 0x0E,W"),
                    BinOp::Shl => self.line("SHL 0x0E,W"),
                    BinOp::Shr => self.line("SHR 0x0E,W"),
                    BinOp::LogicalAnd | BinOp::LogicalOr => unreachable!(),
                    _ => self.cmp(*o)?,
                }
            }
            Expr::Str(_) => return Err("string literal is only valid in puts()".into()),
            Expr::SizeOfName(_) => return Err("internal: sizeof was not lowered".into()),
            Expr::AddrOf(_) => return Err("internal: address-of was not lowered".into()),
            Expr::Call(n, a) => self.call(n, a)?,
        }
        Ok(())
    }
    fn cmp(&mut self, o: BinOp) -> Result<(), String> {
        self.line("CMP 0x0E");
        self.cmp_flags(o)
    }
    fn cmp_flags(&mut self, o: BinOp) -> Result<(), String> {
        let t = self.lab("cmp_t");
        let f = self.lab("cmp_f");
        let e = self.lab("cmp_e");
        match o {
            BinOp::Eq => self.line(&format!("JZ {t}")),
            BinOp::Ne => self.line(&format!("JNZ {t}")),
            BinOp::Lt => self.line(&format!("JNC {t}")),
            BinOp::Ge => self.line(&format!("JC {t}")),
            BinOp::Le => {
                self.line(&format!("JNC {t}"));
                self.line(&format!("JZ {t}"))
            }
            BinOp::Gt => {
                self.line(&format!("JNC {f}"));
                self.line(&format!("JZ {f}"));
                self.line(&format!("JMP {t}"))
            }
            _ => return Err("comparison".into()),
        }
        self.line(&format!("{f}:"));
        self.line("LDI 0");
        self.line(&format!("JMP {e}"));
        self.line(&format!("{t}:"));
        self.line("LDI 1");
        self.line(&format!("{e}:"));
        Ok(())
    }
    fn emit_console_getc_inline(&mut self) {
        let wait = self.lab("console_wait");
        self.line(&format!("{}:", wait));
        self.line("FSR0I 0xFF21");
        self.line("LDB0");
        self.line("ANDI 1");
        self.line(&format!("JZ {}", wait));
        self.line("FSR0I 0xFF20");
        self.line("LDB0");
        self.line("PUSHW");
        self.line("LDI 1");
        self.line("FSR0I 0xFF21");
        self.line("STB0");
        self.line("POPW");
    }

    fn call(&mut self, n: &str, a: &[Expr]) -> Result<(), String> {
        match n {
            "puts" => {
                if a.len() != 1 {
                    return Err("puts expects 1 string literal".into());
                }
                let Expr::Str(text) = &a[0] else {
                    return Err("puts expects a string literal".into());
                };
                self.line("FSR0I 0xFF20");
                for ch in text.bytes().chain([13u8, 10u8]) {
                    self.line(&format!("LDI {}", ch));
                    self.line("STB0")
                }
                self.line("LDI 0");
                return Ok(());
            }
            "putc" => {
                if a.len() != 1 {
                    return Err("putc expects 1 argument".into());
                }
                self.expr(&a[0])?;
                self.line("FSR0I 0xFF20");
                self.line("STB0");
                self.line("LDI 0");
                return Ok(());
            }
            "getc" => {
                if !a.is_empty() {
                    return Err("getc expects 0 arguments".into());
                }
                self.emit_console_getc_inline();
                return Ok(());
            }
            "clock_lo" => {
                if !a.is_empty() {
                    return Err("clock_lo expects 0 arguments".into());
                }
                self.line("FSR0I 0xFF1A");
                self.line("LDW0");
                return Ok(());
            }
            "clock_hi" => {
                if !a.is_empty() {
                    return Err("clock_hi expects 0 arguments".into());
                }
                self.line("FSR0I 0xFF1C");
                self.line("LDW0");
                return Ok(());
            }
            "instr_lo" => {
                if !a.is_empty() {
                    return Err("instr_lo expects 0 arguments".into());
                }
                self.line("FSR0I 0xFF22");
                self.line("LDW0");
                return Ok(());
            }
            "instr_hi" => {
                if !a.is_empty() {
                    return Err("instr_hi expects 0 arguments".into());
                }
                self.line("FSR0I 0xFF24");
                self.line("LDW0");
                return Ok(());
            }
            "asr1" => {
                if a.len() != 1 {
                    return Err("asr1 expects 1 argument".into());
                }
                self.expr(&a[0])?;
                self.line("ASR1W");
                return Ok(());
            }
            "mul_q15" => {
                if a.len() != 2 {
                    return Err("mul_q15 expects 2 arguments".into());
                }
                self.expr(&a[1])?;
                self.line("MOV16 W, 0x0E");
                self.expr(&a[0])?;
                self.line("MULQ15 0x0E,W");
                return Ok(());
            }
            "vload8" | "vload16" => {
                if a.len() != 1 {
                    return Err(format!("{n} expects 1 argument"));
                }
                self.expr(&a[0])?;
                self.line("W2F0");
                self.line(if n == "vload8" { "VLDB0" } else { "VLDW0" });
                return Ok(());
            }
            "vstore8" | "vstore16" => {
                if a.len() != 2 {
                    return Err(format!("{n} expects 2 arguments"));
                }
                self.expr(&a[1])?;
                self.line("PUSHW");
                self.expr(&a[0])?;
                self.line("W2F0");
                self.line("POPW");
                self.line(if n == "vstore8" { "VSTB0" } else { "VSTW0" });
                self.line("LDI 0");
                return Ok(());
            }
            "load8" | "load16" => {
                if a.len() != 1 {
                    return Err(format!("{n} expects 1 argument"));
                }
                if let Expr::Num(q) = &a[0] {
                    if *q <= 0xff {
                        self.line(&format!(
                            "MOV{} 0x{:02X}, W",
                            if n == "load8" { "8" } else { "16" },
                            q
                        ))
                    } else {
                        self.line(&format!("FSR0I 0x{q:04X}"));
                        self.line(if n == "load8" { "LDB0" } else { "LDW0" })
                    }
                } else {
                    self.expr(&a[0])?;
                    self.line("W2F0");
                    self.line(if n == "load8" { "LDB0" } else { "LDW0" })
                }
                return Ok(());
            }
            "store8" | "store16" => {
                if a.len() != 2 {
                    return Err(format!("{n} expects 2 arguments"));
                }
                self.expr(&a[1])?;
                if let Expr::Num(q) = &a[0] {
                    if *q <= 0xff {
                        self.line(&format!(
                            "MOV{} W, 0x{:02X}",
                            if n == "store8" { "8" } else { "16" },
                            q
                        ))
                    } else {
                        self.line(&format!("FSR0I 0x{q:04X}"));
                        self.line(if n == "store8" { "STB0" } else { "STW0" })
                    }
                } else {
                    self.line("PUSHW");
                    self.expr(&a[0])?;
                    self.line("W2F0");
                    self.line("POPW");
                    self.line(if n == "store8" { "STB0" } else { "STW0" })
                }
                self.line("LDI 0");
                return Ok(());
            }
            _ => {}
        }
        let sig = self
            .l
            .funcs
            .get(n)
            .ok_or_else(|| format!("unknown function '{n}'"))?;
        if sig.params.len() != a.len() {
            return Err("argument count mismatch".into());
        }
        let f = self
            .prog
            .functions
            .iter()
            .find(|f| f.name == n)
            .cloned()
            .ok_or_else(|| "missing function".to_string())?;
        for x in a {
            self.expr(x)?;
            self.line("PUSHW");
        }
        for p in f.params.iter().rev() {
            self.line("POPW");
            let v = self
                .l
                .var(n, &p.name)
                .cloned()
                .ok_or_else(|| "missing param".to_string())?;
            self.store(&v)
        }
        self.line(&format!("CALL {n}"));
        Ok(())
    }
}
