use crate::model::*;

fn expr_source(e: &Expr) -> String {
    match e {
        Expr::Num(v) => {
            if *v >= 0x1000 {
                format!("0x{v:04X}")
            } else {
                v.to_string()
            }
        }
        Expr::Var(n) => n.clone(),
        Expr::Str(x) => format!("\"{}\"", x.escape_default()),
        Expr::SizeOfName(n) => format!("sizeof({n})"),
        Expr::AddrOf(n) => format!("&{n}"),
        Expr::Call(n, args) => format!(
            "{}({})",
            n,
            args.iter().map(expr_source).collect::<Vec<_>>().join(", ")
        ),
        Expr::Unary(op, a) => {
            return match op {
                UnOp::Neg => format!("-({})", expr_source(a)),
                UnOp::Not => format!("~({})", expr_source(a)),
                UnOp::LogicalNot => format!("!({})", expr_source(a)),
                UnOp::Inc1 => format!("({} + 1)", expr_source(a)),
                UnOp::Dec1 => format!("({} - 1)", expr_source(a)),
                UnOp::Shl1 => format!("({} << 1)", expr_source(a)),
                UnOp::Shr1 => format!("({} >> 1)", expr_source(a)),
            };
        }
        Expr::Binary(op, a, b) => {
            let s = match op {
                BinOp::LogicalOr => "||",
                BinOp::LogicalAnd => "&&",
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::And => "&",
                BinOp::Or => "|",
                BinOp::Xor => "^",
                BinOp::Shl => "<<",
                BinOp::Shr => ">>",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Gt => ">",
                BinOp::Le => "<=",
                BinOp::Ge => ">=",
            };
            format!("({} {} {})", expr_source(a), s, expr_source(b))
        }
    }
}

fn format_readable(raw: &str) -> String {
    let mut out = String::new();
    for line in raw.lines() {
        let t = line.trim();
        if t.is_empty() {
            out.push('\n');
        } else if t.ends_with(':')
            || t.starts_with('.')
            || t.starts_with(';')
            || t.starts_with('\\')
        {
            out.push_str(t);
            out.push('\n');
        } else {
            out.push_str("    ");
            out.push_str(t);
            out.push('\n');
        }
    }
    out
}

pub fn emit(p: &Program, l: &Layout, opt: OptLevel) -> Result<String, String> {
    let mut e = E {
        out: String::new(),
        n: 0,
        layout: l,
        fun: String::new(),
        loops: Vec::new(),
    };
    e.comment("Generated by SVM-C for the stack-machine target.");
    e.comment(&format!("Optimization: {:?}", opt));
    e.comment("Readable assembly output: stack effects remain visible.");
    e.blank();
    e.line(".load 0x0100");
    e.line(".entry __start");
    e.blank();
    e.line(".proc __start");
    e.comment("program initialization");
    for g in &p.globals {
        if let Some(Expr::Num(v)) = &g.init {
            e.line(&v.to_string());
            let vi = &l.globals[&g.name];
            e.line(&vi.addr.to_string());
            e.line(if vi.ty.size() == 1 { "C!" } else { "!" });
        }
    }
    e.blank();
    e.comment("enter user program");
    e.line("CALL main");
    if l.funcs["main"].ret != Ty::Void {
        e.line("DROP    \\ discard main return value")
    }
    e.line("HALT");
    e.line(".endproc");
    for f in &p.functions {
        e.function(f)?
    }
    Ok(format_readable(&e.out))
}
struct E<'a> {
    out: String,
    n: usize,
    layout: &'a Layout,
    fun: String,
    loops: Vec<(String, String)>, // (continue target, break target)
}
impl<'a> E<'a> {
    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n')
    }
    fn blank(&mut self) {
        if !self.out.ends_with("\n\n") {
            self.out.push('\n')
        }
    }
    fn comment(&mut self, s: &str) {
        self.line(&format!("\\ {s}"))
    }
    fn label(&mut self, p: &str) -> String {
        let x = format!("__{}_{}_{}", self.fun, p, self.n);
        self.n += 1;
        x
    }
    fn var(&self, n: &str) -> Result<VarInfo, String> {
        self.layout
            .var(&self.fun, n)
            .cloned()
            .ok_or_else(|| format!("unknown variable '{n}' in {}", self.fun))
    }
    fn function(&mut self, f: &Function) -> Result<(), String> {
        self.fun = f.name.clone();
        self.loops.clear();
        self.blank();
        self.comment(&format!("function {}", f.name));
        self.line(&format!(".proc {}", f.name));
        for a in f.params.iter().rev() {
            let v = self.var(&a.name)?;
            self.comment(&format!("parameter {} -> 0x{:04X}", a.name, v.addr));
            self.line(&format!("0x{:04X}", v.addr));
            self.line(if v.ty.size() == 1 { "C!" } else { "!" });
        }
        self.stmt(&f.body)?;
        if f.ret != Ty::Void {
            self.line("0")
        }
        self.line("RET");
        self.line(".endproc");
        Ok(())
    }
    fn load(&mut self, v: &VarInfo) {
        self.line(&format!("0x{:04X}", v.addr));
        self.line(if v.ty.size() == 1 { "C@" } else { "@" });
    }
    fn store(&mut self, v: &VarInfo) {
        self.line(&format!("0x{:04X}", v.addr));
        self.line(if v.ty.size() == 1 { "C!" } else { "!" });
    }
    fn stmt(&mut self, s: &Stmt) -> Result<(), String> {
        match s {
            Stmt::Block(v) => {
                for x in v {
                    self.stmt(x)?
                }
            }
            Stmt::Var(v) => {
                if let Some(x) = &v.init {
                    self.comment(&format!(
                        "{} {} = {};",
                        if v.ty.size() == 1 { "u8" } else { "u16" },
                        v.name,
                        expr_source(x)
                    ));
                    self.expr(x)?;
                    let z = self.var(&v.name)?;
                    self.store(&z)
                }
            }
            Stmt::Assign(n, x) => {
                self.comment(&format!("{} = {};", n, expr_source(x)));
                self.expr(x)?;
                let v = self.var(n)?;
                self.store(&v)
            }
            Stmt::Expr(x) => {
                self.comment(&format!("{};", expr_source(x)));
                self.expr(x)?;
                if self.expr_has_value(x)? {
                    self.line("DROP")
                }
            }
            Stmt::If(c, a, b) => {
                self.comment(&format!("if ({})", expr_source(c)));
                let els = self.label("else");
                let end = self.label("ifend");
                self.expr(c)?;
                self.line(&format!("JZ {els}"));
                self.stmt(a)?;
                self.line(&format!("JMP {end}"));
                self.line(&format!("{els}:"));
                if let Some(b) = b {
                    self.stmt(b)?
                }
                self.line(&format!("{end}:"));
            }
            Stmt::While(c, b) => {
                self.comment(&format!("while ({})", expr_source(c)));
                let top = self.label("while");
                let end = self.label("wend");
                self.line(&format!("{top}:"));
                self.expr(c)?;
                self.line(&format!("JZ {end}"));
                self.loops.push((top.clone(), end.clone()));
                self.stmt(b)?;
                self.loops.pop();
                self.line(&format!("JMP {top}"));
                self.line(&format!("{end}:"));
            }
            Stmt::DoWhile(b, c) => {
                let top = self.label("do");
                let cond = self.label("docond");
                let end = self.label("doend");
                self.line(&format!("{top}:"));
                self.loops.push((cond.clone(), end.clone()));
                self.stmt(b)?;
                self.loops.pop();
                self.line(&format!("{cond}:"));
                self.expr(c)?;
                self.line(&format!("JZ {end}"));
                self.line(&format!("JMP {top}"));
                self.line(&format!("{end}:"));
            }
            Stmt::Break => {
                let (_, b) = self.loops.last().ok_or("break outside loop")?.clone();
                self.line(&format!("JMP {b}"));
            }
            Stmt::Continue => {
                let (c, _) = self.loops.last().ok_or("continue outside loop")?.clone();
                self.line(&format!("JMP {c}"));
            }
            Stmt::For(i, c, st, b) => {
                self.comment("for loop");
                if let Some(i) = i {
                    self.stmt(i)?
                }
                let top = self.label("for");
                let step = self.label("fstep");
                let end = self.label("fend");
                self.line(&format!("{top}:"));
                if let Some(c) = c {
                    self.expr(c)?;
                    self.line(&format!("JZ {end}"));
                }
                self.loops.push((step.clone(), end.clone()));
                self.stmt(b)?;
                self.loops.pop();
                self.line(&format!("{step}:"));
                if let Some(st) = st {
                    self.stmt(st)?
                }
                self.line(&format!("JMP {top}"));
                self.line(&format!("{end}:"));
            }
            Stmt::Return(x) => {
                if let Some(x) = x {
                    self.comment(&format!("return {};", expr_source(x)));
                    self.expr(x)?
                } else {
                    self.comment("return;")
                }
                self.line("RET")
            }
            Stmt::Empty => {}
        }
        Ok(())
    }
    fn expr_has_value(&self, x: &Expr) -> Result<bool, String> {
        match x {
            Expr::Call(n, _) => {
                if let Some(sig) = crate::semantic::builtin_sig(n) {
                    return Ok(sig.ret != Ty::Void);
                }
                Ok(self
                    .layout
                    .funcs
                    .get(n)
                    .map(|s| s.ret != Ty::Void)
                    .unwrap_or(true))
            }
            _ => Ok(true),
        }
    }
    fn expr(&mut self, x: &Expr) -> Result<(), String> {
        match x {
            Expr::Num(v) => self.line(&v.to_string()),
            Expr::Var(n) => {
                let v = self.var(n)?;
                self.load(&v)
            }
            Expr::Unary(op, a) => {
                self.expr(a)?;
                self.line(match op {
                    UnOp::Neg => "NEG",
                    UnOp::Not => "NOT",
                    UnOp::LogicalNot => "0=",
                    UnOp::Inc1 => "INC",
                    UnOp::Dec1 => "DEC",
                    UnOp::Shl1 => "SHL1",
                    UnOp::Shr1 => "SHR1",
                })
            }
            Expr::Binary(op, a, b) => {
                if matches!(op, BinOp::LogicalAnd | BinOp::LogicalOr) {
                    let end = self.label("logic_end");
                    if matches!(op, BinOp::LogicalAnd) {
                        let false_l = self.label("logic_false");
                        self.expr(a)?;
                        self.line(&format!("JZ {false_l}"));
                        self.expr(b)?;
                        self.line(&format!("JZ {false_l}"));
                        self.line("1");
                        self.line(&format!("JMP {end}"));
                        self.line(&format!("{false_l}:"));
                        self.line("0");
                    } else {
                        let rhs_l = self.label("logic_rhs");
                        let false_l = self.label("logic_false");
                        self.expr(a)?;
                        self.line(&format!("JZ {rhs_l}"));
                        self.line("1");
                        self.line(&format!("JMP {end}"));
                        self.line(&format!("{rhs_l}:"));
                        self.expr(b)?;
                        self.line(&format!("JZ {false_l}"));
                        self.line("1");
                        self.line(&format!("JMP {end}"));
                        self.line(&format!("{false_l}:"));
                        self.line("0");
                    }
                    self.line(&format!("{end}:"));
                    return Ok(());
                }
                self.expr(a)?;
                self.expr(b)?;
                match op {
                    BinOp::Add => self.line("+"),
                    BinOp::Sub => self.line("-"),
                    BinOp::Mul => self.line("*"),
                    BinOp::Div => self.line("/"),
                    BinOp::Mod => self.line("MOD"),
                    BinOp::And => self.line("AND"),
                    BinOp::Or => self.line("OR"),
                    BinOp::Xor => self.line("XOR"),
                    BinOp::Shl => self.line("SHL"),
                    BinOp::Shr => self.line("SHR"),
                    // The Stack ISA follows the Forth convention for comparisons:
                    // true is 0xFFFF.  SVM-C, however, requires relational operators
                    // to produce the numeric value 1.  Normalize here so a boolean
                    // can safely participate in arithmetic (for example carry = lo < al).
                    BinOp::Eq => {
                        self.line("=");
                        self.line("1");
                        self.line("AND");
                    }
                    BinOp::Ne => {
                        self.line("<>");
                        self.line("1");
                        self.line("AND");
                    }
                    BinOp::Lt => {
                        self.line("U<");
                        self.line("1");
                        self.line("AND");
                    }
                    BinOp::Gt => {
                        self.line("U>");
                        self.line("1");
                        self.line("AND");
                    }
                    BinOp::Le => {
                        self.line("U>");
                        self.line("0=");
                        self.line("1");
                        self.line("AND")
                    }
                    BinOp::Ge => {
                        self.line("U<");
                        self.line("0=");
                        self.line("1");
                        self.line("AND")
                    }
                    BinOp::LogicalAnd | BinOp::LogicalOr => unreachable!(),
                }
            }
            Expr::Str(_) => return Err("string literal is only valid in puts()".into()),
            Expr::SizeOfName(_) => return Err("internal: sizeof was not lowered".into()),
            Expr::AddrOf(_) => return Err("internal: address-of was not lowered".into()),
            Expr::Call(n, a) => self.call(n, a)?,
        }
        Ok(())
    }
    fn emit_console_getc_inline(&mut self) {
        let wait = self.label("console_wait");
        self.line(&format!("{}:", wait));
        self.line("0xFF21");
        self.line("C@");
        self.line("1");
        self.line("AND");
        self.line(&format!("JZ {}", wait));
        self.line("0xFF20");
        self.line("C@");
        self.line("1");
        self.line("0xFF21");
        self.line("C!");
    }

    fn call(&mut self, n: &str, a: &[Expr]) -> Result<(), String> {
        match n {
            "puts" => {
                if a.len() != 1 {
                    return Err("puts expects 1 string literal".into());
                }
                let Expr::Str(text) = &a[0] else {
                    return Err("puts expects a string literal".into());
                };
                for ch in text.bytes().chain([13u8, 10u8]) {
                    self.line(&ch.to_string());
                    self.line("0xFF20 C!");
                }
                return Ok(());
            }
            "putc" => {
                if a.len() != 1 {
                    return Err("putc expects 1 argument".into());
                }
                self.expr(&a[0])?;
                self.line("0xFF20 C!");
                return Ok(());
            }
            "getc" => {
                if !a.is_empty() {
                    return Err("getc expects 0 arguments".into());
                }
                self.emit_console_getc_inline();
                return Ok(());
            }
            "clock_lo" => {
                if !a.is_empty() {
                    return Err("clock_lo expects 0 arguments".into());
                }
                self.line("0xFF1A");
                self.line("@");
                return Ok(());
            }
            "clock_hi" => {
                if !a.is_empty() {
                    return Err("clock_hi expects 0 arguments".into());
                }
                self.line("0xFF1C");
                self.line("@");
                return Ok(());
            }
            "instr_lo" => {
                if !a.is_empty() {
                    return Err("instr_lo expects 0 arguments".into());
                }
                self.line("0xFF22");
                self.line("@");
                return Ok(());
            }
            "instr_hi" => {
                if !a.is_empty() {
                    return Err("instr_hi expects 0 arguments".into());
                }
                self.line("0xFF24");
                self.line("@");
                return Ok(());
            }
            "asr1" => {
                if a.len() != 1 {
                    return Err("asr1 expects 1 argument".into());
                }
                self.expr(&a[0])?;
                self.line("ASR1");
                return Ok(());
            }
            "mul_q15" => {
                if a.len() != 2 {
                    return Err("mul_q15 expects 2 arguments".into());
                }
                self.expr(&a[0])?;
                self.expr(&a[1])?;
                self.line("MULQ15");
                return Ok(());
            }
            "vload8" | "vload16" => {
                if a.len() != 1 {
                    return Err(format!("{n} expects 1 argument"));
                }
                self.expr(&a[0])?;
                self.line(if n == "vload8" { "VC@" } else { "V@" });
                return Ok(());
            }
            "vstore8" | "vstore16" => {
                if a.len() != 2 {
                    return Err(format!("{n} expects 2 arguments"));
                }
                self.expr(&a[1])?;
                self.expr(&a[0])?;
                self.line(if n == "vstore8" { "VC!" } else { "V!" });
                return Ok(());
            }
            "load8" | "load16" => {
                if a.len() != 1 {
                    return Err(format!("{n} expects 1 argument"));
                }
                self.expr(&a[0])?;
                self.line(if n == "load8" { "C@" } else { "@" });
                return Ok(());
            }
            "store8" | "store16" => {
                if a.len() != 2 {
                    return Err(format!("{n} expects 2 arguments"));
                }
                self.expr(&a[1])?;
                self.expr(&a[0])?;
                self.line(if n == "store8" { "C!" } else { "!" });
                return Ok(());
            }
            _ => {}
        }
        let sig = self
            .layout
            .funcs
            .get(n)
            .ok_or_else(|| format!("unknown function '{n}'"))?;
        if sig.params.len() != a.len() {
            return Err(format!(
                "function '{n}' expects {} arguments",
                sig.params.len()
            ));
        }
        for x in a {
            self.expr(x)?
        }
        self.line(&format!("CALL {n}"));
        Ok(())
    }
}
