use crate::{backend_register, model::*};

fn ops(s: &str) -> Vec<String> {
    s.split(',')
        .map(|x| x.trim().to_string())
        .filter(|x| !x.is_empty())
        .collect()
}
fn ptr_reg(s: &str) -> Result<String, String> {
    let t = s.trim();
    if !(t.starts_with('[') && t.ends_with(']')) {
        return Err(format!("expected [Rn], got {s}"));
    }
    Ok(t[1..t.len() - 1]
        .trim()
        .trim_end_matches('+')
        .trim_start_matches('-')
        .trim()
        .to_string())
}
fn bin(out: &mut String, op: &str, d: &str, s: &str) {
    out.push_str(&format!(
        "    MOV {d},ALU.X\n    MOV {s},ALU.{op}\n    MOV ALU.OUT,{d}\n"
    ));
}
fn imm(out: &mut String, op: &str, d: &str, v: &str) {
    out.push_str(&format!(
        "    MOV {d},ALU.X\n    MOV {v},ALU.{op}\n    MOV ALU.OUT,{d}\n"
    ));
}
fn unary(out: &mut String, op: &str, d: &str) {
    out.push_str(&format!("    MOV {d},ALU.{op}\n    MOV ALU.OUT,{d}\n"));
}

fn translate(register_asm: &str) -> Result<String, String> {
    let mut out = String::from(
        "; Generated by SVM-C for the TTA16 target.\n; ALU operations are triggered by transports to ALU.* ports.\n",
    );
    for raw in register_asm.lines() {
        let t = raw.trim();
        if t.is_empty() {
            out.push('\n');
            continue;
        }
        if t.starts_with(';') {
            continue;
        }
        if t.starts_with('.') || t.ends_with(':') {
            out.push_str(t);
            out.push('\n');
            continue;
        }
        let mut p = t.splitn(2, char::is_whitespace);
        let m = p.next().unwrap_or("").to_ascii_uppercase();
        let a = ops(p.next().unwrap_or(""));
        match m.as_str() {
            "NOP" => out.push_str("    MOV R0,R0\n"),
            "HALT" => out.push_str("    MOV ZERO,CTRL.HALT\n"),
            "RET" => out.push_str("    MOV CTRL.RETADDR,CTRL.JMP\n"),
            "IRET" => out.push_str("    MOV CTRL.IRETADDR,CTRL.JMP\n"),
            "EI" => out.push_str("    MOV ZERO,CTRL.EI\n"),
            "DI" => out.push_str("    MOV ZERO,CTRL.DI\n"),
            "JMP" | "JZ" | "JNZ" | "JC" | "JNC" | "JN" | "JNN" | "CALL" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                let d = match m.as_str() {
                    "JMP" => "CTRL.JMP",
                    "JZ" => "CTRL.JZ",
                    "JNZ" => "CTRL.JNZ",
                    "JC" => "CTRL.JC",
                    "JNC" => "CTRL.JNC",
                    "JN" => "CTRL.JN",
                    "JNN" => "CTRL.JNN",
                    _ => "CTRL.CALL",
                };
                out.push_str(&format!("    MOV {},{}\n", a[0], d));
            }
            "MOVI" => {
                if a.len() != 2 {
                    return Err("bad MOVI".into());
                }
                out.push_str(&format!("    MOV {},{}\n", a[1], a[0]));
            }
            "MOV" => {
                if a.len() != 2 {
                    return Err("bad MOV".into());
                }
                out.push_str(&format!("    MOV {},{}\n", a[1], a[0]));
            }
            "ADD" | "SUB" | "AND" | "OR" | "XOR" | "MUL" | "DIV" | "MOD" | "SHL" | "SHR"
            | "CMP" | "ADC" | "SBC" | "MULHU" | "MULQ15" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                bin(&mut out, &m, &a[0], &a[1]);
            }
            "ADDI" | "SUBI" | "ANDI" | "ORI" | "XORI" | "CMPI" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let op = match m.as_str() {
                    "ADDI" => "ADD",
                    "SUBI" => "SUB",
                    "ANDI" => "AND",
                    "ORI" => "OR",
                    "XORI" => "XOR",
                    _ => "CMP",
                };
                imm(&mut out, op, &a[0], &a[1]);
            }
            "NOT" | "NEG" | "ASR1" | "SHL1" | "SHR1" | "RCR1" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                unary(&mut out, &m, &a[0]);
            }
            "INC" | "DEC" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                imm(&mut out, if m == "INC" { "ADD" } else { "SUB" }, &a[0], "1");
            }
            "PUSH" => {
                if a.len() != 1 {
                    return Err("bad PUSH".into());
                }
                out.push_str(&format!("    MOV {},STACK.PUSH\n", a[0]));
            }
            "POP" => {
                if a.len() != 1 {
                    return Err("bad POP".into());
                }
                out.push_str(&format!("    MOV STACK.POP,{}\n", a[0]));
            }
            "ZLOAD8" | "ZLOAD16" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                out.push_str(&format!(
                    "    MOV {},MEM.ADDR\n    MOV {},R0\n",
                    a[0],
                    if m == "ZLOAD8" { "MEM.R8" } else { "MEM.R16" }
                ));
            }
            "ZSTORE8" | "ZSTORE16" => {
                if a.len() != 1 {
                    return Err(format!("bad {m}"));
                }
                out.push_str(&format!(
                    "    MOV {},MEM.ADDR\n    MOV R0,{}\n",
                    a[0],
                    if m == "ZSTORE8" { "MEM.W8" } else { "MEM.W16" }
                ));
            }
            "LOAD8" | "LOAD16" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let pr = ptr_reg(&a[1])?;
                out.push_str(&format!(
                    "    MOV {pr},MEM.ADDR\n    MOV {},{}\n",
                    if m == "LOAD8" { "MEM.R8" } else { "MEM.R16" },
                    a[0]
                ));
            }
            "STORE8" | "STORE16" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let pr = ptr_reg(&a[0])?;
                out.push_str(&format!(
                    "    MOV {pr},MEM.ADDR\n    MOV {},{}\n",
                    a[1],
                    if m == "STORE8" { "MEM.W8" } else { "MEM.W16" }
                ));
            }
            "VLOAD8" | "VLOAD16" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let pr = ptr_reg(&a[1])?;
                out.push_str(&format!(
                    "    MOV {pr},VMEM.ADDR\n    MOV {},{}\n",
                    if m == "VLOAD8" { "VMEM.R8" } else { "VMEM.R16" },
                    a[0]
                ));
            }
            "VSTORE8" | "VSTORE16" => {
                if a.len() != 2 {
                    return Err(format!("bad {m}"));
                }
                let pr = ptr_reg(&a[0])?;
                out.push_str(&format!(
                    "    MOV {pr},VMEM.ADDR\n    MOV {},{}\n",
                    a[1],
                    if m == "VSTORE8" {
                        "VMEM.W8"
                    } else {
                        "VMEM.W16"
                    }
                ));
            }
            _ => return Err(format!("TTA lowering does not know instruction: {t}")),
        }
    }
    Ok(out)
}

pub fn emit(p: &Program, l: &Layout, opt: OptLevel) -> Result<String, String> {
    translate(&backend_register::emit(p, l, opt)?)
}
