//! Direct CLIR -> Memory2Memory lowering.
//! CLIR temporaries are ordinary memory operands on this target.

use super::layout::{Layout, Var, lines, parse_call, parse_fn_header, width_of};

fn mem(addr: u16) -> String {
    format!("[0x{addr:04X}]")
}

fn temp(layout: &Layout, function: &str, name: &str) -> Result<String, String> {
    Ok(mem(layout.resolve(function, name)?.addr))
}

fn store_var(out: &mut String, var: &Var, src: &str) {
    let op = if var.width == 1 { "MOV8" } else { "MOV16" };
    out.push_str(&format!("    {op} {}, {src}\n", mem(var.addr)));
}

fn normalize(out: &mut String, dst: &str, ty: &str, scratch: u16, label_id: &mut usize) {
    match ty {
        "bool" => out.push_str(&format!("    AND16 {dst}, 1\n")),
        "u8" => out.push_str(&format!("    AND16 {dst}, 0x00FF\n")),
        "i8" => {
            let n = *label_id;
            *label_id += 1;
            let s = mem(scratch);
            out.push_str(&format!(
                "    AND16 {dst}, 0x00FF\n    MOV16 {s}, {dst}\n    AND16 {s}, 0x0080\n    CMP16 {s}, 0\n    JZ __cl_m2m_norm_{n}\n    OR16 {dst}, 0xFF00\n__cl_m2m_norm_{n}:\n"
            ));
        }
        _ => {}
    }
}

fn emit_startup(out: &mut String, layout: &Layout) {
    out.push_str("; Generated by SVM C-Lite for the Memory2Memory16 target.\n");
    out.push_str(".load 0x0100\n.entry __start\n\n.proc __start\n");
    for (name, (_, init)) in &layout.globals {
        let Some(value) = init else { continue };
        let var = &layout.vars[name];
        let op = if var.width == 1 { "MOV8" } else { "MOV16" };
        out.push_str(&format!("    {op} {}, {value}\n", mem(var.addr)));
    }
    out.push_str("    CALL main\n    HALT\n.endproc\n\n");
}

fn emit_compare(
    out: &mut String,
    layout: &Layout,
    function: &str,
    dst: &str,
    op: &str,
    ty: &str,
    left: &str,
    right: &str,
    scratch: [u16; 3],
    label_id: &mut usize,
) -> Result<(), String> {
    let l = temp(layout, function, left)?;
    let r = temp(layout, function, right)?;
    let [sa, sb, _] = scratch;
    let (cmp_l, cmp_r) = if matches!(ty, "i8" | "i16") {
        let bias = if ty == "i8" { "0x0080" } else { "0x8000" };
        let a = mem(sa);
        let b = mem(sb);
        out.push_str(&format!(
            "    MOV16 {a}, {l}\n    XOR16 {a}, {bias}\n    MOV16 {b}, {r}\n    XOR16 {b}, {bias}\n"
        ));
        (a, b)
    } else {
        (l, r)
    };

    out.push_str(&format!("    CMP16 {cmp_l}, {cmp_r}\n"));
    let n = *label_id;
    *label_id += 1;
    let t = format!("__cl_m2m_cmp_t_{n}");
    let f = format!("__cl_m2m_cmp_f_{n}");
    let e = format!("__cl_m2m_cmp_e_{n}");
    match op {
        "eq" => out.push_str(&format!("    JZ {t}\n")),
        "ne" => out.push_str(&format!("    JNZ {t}\n")),
        "lt" => out.push_str(&format!("    JNC {t}\n")),
        "ge" => out.push_str(&format!("    JC {t}\n")),
        "le" => out.push_str(&format!("    JNC {t}\n    JZ {t}\n")),
        "gt" => out.push_str(&format!("    JNC {f}\n    JZ {f}\n    JMP {t}\n")),
        _ => return Err(format!("bad compare {op}")),
    }
    out.push_str(&format!(
        "{f}:\n    MOV16 {dst}, 0\n    JMP {e}\n{t}:\n    MOV16 {dst}, 1\n{e}:\n"
    ));
    Ok(())
}

fn emit_signed_divmod(
    out: &mut String,
    layout: &Layout,
    function: &str,
    dst: &str,
    op: &str,
    ty: &str,
    left: &str,
    right: &str,
    scratch: [u16; 3],
    label_id: &mut usize,
) -> Result<(), String> {
    let [aa, bb, ss] = scratch;
    let a = mem(aa);
    let b = mem(bb);
    let sign = mem(ss);
    let l = temp(layout, function, left)?;
    let r = temp(layout, function, right)?;
    out.push_str(&format!("    MOV16 {a}, {l}\n    MOV16 {b}, {r}\n"));
    normalize(out, &a, ty, ss, label_id);
    normalize(out, &b, ty, ss, label_id);

    let n = *label_id;
    *label_id += 1;
    out.push_str(&format!(
        "    MOV16 {sign}, 0\n    CMP16 {a}, 0\n    JNN __cl_m2m_sd_a_{n}\n    NEG16 {a}\n    MOV16 {sign}, 1\n__cl_m2m_sd_a_{n}:\n    CMP16 {b}, 0\n    JNN __cl_m2m_sd_b_{n}\n    NEG16 {b}\n"
    ));
    if op == "div" {
        out.push_str(&format!("    XOR16 {sign}, 1\n"));
    }
    out.push_str(&format!(
        "__cl_m2m_sd_b_{n}:\n    MOV16 {dst}, {a}\n    {} {dst}, {b}\n    CMP16 {sign}, 0\n    JZ __cl_m2m_sd_e_{n}\n    NEG16 {dst}\n__cl_m2m_sd_e_{n}:\n",
        if op == "div" { "DIV16" } else { "MOD16" }
    ));
    normalize(out, dst, ty, ss, label_id);
    Ok(())
}

pub fn lower(clir: &str) -> Result<String, String> {
    let lines = lines(clir);
    let mut layout = Layout::scan(&lines, true)?;
    let scratch = [layout.scratch(2)?, layout.scratch(2)?, layout.scratch(2)?];
    let mut out = String::new();
    emit_startup(&mut out, &layout);
    let mut current = String::new();
    let mut label_id = 0usize;

    for line in lines {
        if line.starts_with("global ") || line.starts_with("local ") {
            continue;
        }
        if line.starts_with("fn ") {
            let (name, _) = parse_fn_header(line)?;
            current = name.clone();
            out.push_str(&format!(".proc {name}\n"));
            continue;
        }
        if line == "end" {
            out.push_str(".endproc\n\n");
            current.clear();
            continue;
        }
        if line.ends_with(':') {
            out.push_str(&format!("{}__{}\n", current, line));
            continue;
        }

        if let Some(rest) = line.strip_prefix("const.") {
            let (_, args) = rest.split_once(' ').ok_or("bad const")?;
            let (dst, value) = args.split_once(',').ok_or("bad const")?;
            out.push_str(&format!(
                "    MOV16 {}, {}\n",
                temp(&layout, &current, dst.trim())?,
                value.trim()
            ));
            continue;
        }
        if let Some(rest) = line.strip_prefix("load.") {
            let (ty, args) = rest.split_once(' ').ok_or("bad load")?;
            let (dst, name) = args.split_once(',').ok_or("bad load")?;
            let d = temp(&layout, &current, dst.trim())?;
            let v = layout.resolve(&current, name.trim())?;
            if width_of(ty) == 1 {
                out.push_str(&format!(
                    "    MOV16 {d}, 0\n    MOV8 {d}, {}\n",
                    mem(v.addr)
                ));
            } else {
                out.push_str(&format!("    MOV16 {d}, {}\n", mem(v.addr)));
            }
            normalize(&mut out, &d, ty, scratch[2], &mut label_id);
            continue;
        }
        if let Some(rest) = line.strip_prefix("store.") {
            let (_, args) = rest.split_once(' ').ok_or("bad store")?;
            let (name, src) = args.split_once(',').ok_or("bad store")?;
            let var = layout.resolve(&current, name.trim())?;
            store_var(&mut out, &var, &temp(&layout, &current, src.trim())?);
            continue;
        }
        if let Some(rest) = line.strip_prefix("addr ") {
            let (dst, name) = rest.split_once(',').ok_or("bad addr")?;
            let var = layout.resolve(&current, name.trim())?;
            out.push_str(&format!(
                "    MOV16 {}, 0x{:04X}\n",
                temp(&layout, &current, dst.trim())?,
                var.addr
            ));
            continue;
        }
        if let Some(rest) = line.strip_prefix("index ") {
            let p = rest.split(',').map(str::trim).collect::<Vec<_>>();
            if p.len() != 4 {
                return Err("bad index".into());
            }
            let d = temp(&layout, &current, p[0])?;
            let base = temp(&layout, &current, p[1])?;
            let idx = temp(&layout, &current, p[2])?;
            let s = mem(scratch[0]);
            out.push_str(&format!("    MOV16 {d}, {base}\n"));
            if p[3] == "2" {
                out.push_str(&format!(
                    "    MOV16 {s}, {idx}\n    SHL1 {s}\n    ADD16 {d}, {s}\n"
                ));
            } else {
                out.push_str(&format!("    ADD16 {d}, {idx}\n"));
            }
            continue;
        }
        if line.starts_with("loadmem") {
            let volatile = line.starts_with("loadmemv");
            let dot = line.find('.').ok_or("bad loadmem")?;
            let (ty, args) = line[dot + 1..].split_once(' ').ok_or("bad loadmem")?;
            let (dst, address) = args.split_once(',').ok_or("bad loadmem")?;
            let d = temp(&layout, &current, dst.trim())?;
            out.push_str(&format!(
                "    MOVA A0, {}\n",
                temp(&layout, &current, address.trim())?
            ));
            match (volatile, width_of(ty)) {
                (false, 1) => out.push_str(&format!("    MOV16 {d}, 0\n    MOV8 {d}, [A0]\n")),
                (false, _) => out.push_str(&format!("    MOV16 {d}, [A0]\n")),
                (true, 1) => out.push_str(&format!("    MOV16 {d}, 0\n    VLD8 {d}, [A0]\n")),
                (true, _) => out.push_str(&format!("    VLD16 {d}, [A0]\n")),
            }
            normalize(&mut out, &d, ty, scratch[2], &mut label_id);
            continue;
        }
        if line.starts_with("storemem") {
            let volatile = line.starts_with("storememv");
            let dot = line.find('.').ok_or("bad storemem")?;
            let (ty, args) = line[dot + 1..].split_once(' ').ok_or("bad storemem")?;
            let (address, value) = args.split_once(',').ok_or("bad storemem")?;
            out.push_str(&format!(
                "    MOVA A0, {}\n",
                temp(&layout, &current, address.trim())?
            ));
            let v = temp(&layout, &current, value.trim())?;
            let op = match (volatile, width_of(ty)) {
                (false, 1) => "MOV8",
                (false, _) => "MOV16",
                (true, 1) => "VST8",
                (true, _) => "VST16",
            };
            out.push_str(&format!("    {op} [A0], {v}\n"));
            continue;
        }
        if line.starts_with("drop ") {
            continue;
        }
        if let Some(label) = line.strip_prefix("jmp ") {
            out.push_str(&format!("    JMP {current}__{}\n", label.trim()));
            continue;
        }
        if let Some(rest) = line.strip_prefix("jz ") {
            let (value, label) = rest.split_once(',').ok_or("bad jz")?;
            out.push_str(&format!(
                "    CMP16 {}, 0\n    JZ {current}__{}\n",
                temp(&layout, &current, value.trim())?,
                label.trim()
            ));
            continue;
        }
        if line == "ret" {
            out.push_str("    RET\n");
            continue;
        }
        if let Some(value) = line.strip_prefix("ret ") {
            out.push_str(&format!(
                "    MOV16 [0x0000], {}\n    RET\n",
                temp(&layout, &current, value.trim())?
            ));
            continue;
        }
        if line.starts_with("call") {
            let (dst, name, args) = parse_call(line)?;
            let function = layout
                .funcs
                .get(name)
                .ok_or_else(|| format!("unknown call target {name}"))?;
            if args.len() != function.params.len() {
                return Err(format!("call arity mismatch for {name}"));
            }
            for (arg, (param, _)) in args.iter().zip(&function.params) {
                let slot = layout.resolve(name, param)?;
                store_var(&mut out, &slot, &temp(&layout, &current, arg)?);
            }
            out.push_str(&format!("    CALL {name}\n"));
            if let Some(dst) = dst {
                out.push_str(&format!(
                    "    MOV16 {}, [0x0000]\n",
                    temp(&layout, &current, dst)?
                ));
            }
            continue;
        }

        if let Some((op_ty, args)) = line.split_once(' ') {
            if let Some((op, ty)) = op_ty.split_once('.') {
                if matches!(op, "neg" | "not") {
                    let (dst, src) = args.split_once(',').ok_or("bad unary")?;
                    let d = temp(&layout, &current, dst.trim())?;
                    out.push_str(&format!(
                        "    MOV16 {d}, {}\n    {}16 {d}\n",
                        temp(&layout, &current, src.trim())?,
                        if op == "neg" { "NEG" } else { "NOT" }
                    ));
                    normalize(&mut out, &d, ty, scratch[2], &mut label_id);
                    continue;
                }
                let p = args.split(',').map(str::trim).collect::<Vec<_>>();
                if p.len() != 3 {
                    return Err(format!("bad binary CLIR: {line}"));
                }
                let d = temp(&layout, &current, p[0])?;
                if matches!(op, "eq" | "ne" | "lt" | "le" | "gt" | "ge") {
                    emit_compare(
                        &mut out,
                        &layout,
                        &current,
                        &d,
                        op,
                        ty,
                        p[1],
                        p[2],
                        scratch,
                        &mut label_id,
                    )?;
                } else if matches!(op, "div" | "mod") && matches!(ty, "i8" | "i16") {
                    emit_signed_divmod(
                        &mut out,
                        &layout,
                        &current,
                        &d,
                        op,
                        ty,
                        p[1],
                        p[2],
                        scratch,
                        &mut label_id,
                    )?;
                } else {
                    let asm = match op {
                        "add" => "ADD16",
                        "sub" => "SUB16",
                        "mul" => "MUL16",
                        "div" => "DIV16",
                        "mod" => "MOD16",
                        "and" => "AND16",
                        "or" => "OR16",
                        "xor" => "XOR16",
                        "shl" => "SHL16",
                        "shr" => "SHR16",
                        _ => return Err(format!("unsupported Memory2Memory CLIR op {op}")),
                    };
                    out.push_str(&format!(
                        "    MOV16 {d}, {}\n    {asm} {d}, {}\n",
                        temp(&layout, &current, p[1])?,
                        temp(&layout, &current, p[2])?
                    ));
                    normalize(&mut out, &d, ty, scratch[2], &mut label_id);
                }
                continue;
            }
        }
        return Err(format!("unsupported Memory2Memory CLIR line: {line}"));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lowers_clir_as_memory_operations() {
        let clir = "fn main() -> u16\n  const.u16 %0, 7\n  const.u16 %1, 5\n  mul.u16 %2, %0, %1\n  ret %2\nend\n";
        let asm = lower(clir).unwrap();
        assert!(asm.contains("MUL16"));
        assert!(!asm.contains(" R0"));
    }
}
