//! Direct CLIR -> TTA16 lowering.
//! The backend emits transports directly to ALU/MEM/CTRL ports.

use super::layout::{Layout, Var, lines, parse_call, parse_fn_header, width_of};

#[derive(Default)]
struct Resident {
    temp: Option<String>,
}

impl Resident {
    fn is(&self, temp: &str) -> bool {
        self.temp.as_deref() == Some(temp)
    }

    fn set(&mut self, temp: &str) {
        self.temp = Some(temp.to_string());
    }

    fn clear(&mut self) {
        self.temp = None;
    }

    fn take(&mut self) -> Option<String> {
        self.temp.take()
    }
}

fn mov(out: &mut String, src: impl AsRef<str>, dst: impl AsRef<str>) {
    out.push_str(&format!("    MOV {},{}\n", src.as_ref(), dst.as_ref()));
}

fn alu_bin(out: &mut String, op: &str, left: &str, right: &str, dst: &str) {
    mov(out, left, "ALU.X");
    mov(out, right, format!("ALU.{op}"));
    mov(out, "ALU.OUT", dst);
}

fn alu_cmp(out: &mut String, left: &str, right: &str) {
    mov(out, left, "ALU.X");
    mov(out, right, "ALU.CMP");
}

fn alu_unary(out: &mut String, op: &str, src: &str, dst: &str) {
    mov(out, src, format!("ALU.{op}"));
    mov(out, "ALU.OUT", dst);
}

fn load_addr(out: &mut String, addr: u16, dst: &str, width: u16, volatile: bool) {
    mov(
        out,
        format!("0x{addr:04X}"),
        if volatile { "VMEM.ADDR" } else { "MEM.ADDR" },
    );
    let src = match (volatile, width) {
        (false, 1) => "MEM.R8",
        (false, _) => "MEM.R16",
        (true, 1) => "VMEM.R8",
        (true, _) => "VMEM.R16",
    };
    mov(out, src, dst);
}

fn store_addr(out: &mut String, addr: u16, src: &str, width: u16, volatile: bool) {
    mov(
        out,
        format!("0x{addr:04X}"),
        if volatile { "VMEM.ADDR" } else { "MEM.ADDR" },
    );
    let dst = match (volatile, width) {
        (false, 1) => "MEM.W8",
        (false, _) => "MEM.W16",
        (true, 1) => "VMEM.W8",
        (true, _) => "VMEM.W16",
    };
    mov(out, src, dst);
}

fn spill_resident(
    out: &mut String,
    layout: &Layout,
    function: &str,
    resident: &mut Resident,
) -> Result<(), String> {
    let Some(temp) = resident.take() else {
        return Ok(());
    };
    let var = layout.resolve(function, &temp)?;
    store_addr(out, var.addr, "R0", 2, false);
    Ok(())
}

fn load_temp(
    out: &mut String,
    layout: &Layout,
    function: &str,
    name: &str,
    reg: &str,
    resident: &mut Resident,
) -> Result<(), String> {
    if resident.is(name) {
        if reg != "R0" {
            mov(out, "R0", reg);
        }
        resident.clear();
        return Ok(());
    }

    if reg == "R0" {
        spill_resident(out, layout, function, resident)?;
    }
    let var = layout.resolve(function, name)?;
    load_addr(out, var.addr, reg, 2, false);
    Ok(())
}

fn keep_temp(name: &str, resident: &mut Resident) {
    resident.set(name);
}

fn store_var(out: &mut String, var: &Var, reg: &str) {
    store_addr(out, var.addr, reg, var.width, false);
}

fn branch(out: &mut String, label: &str, port: &str) {
    mov(out, label, port);
}

fn normalize(out: &mut String, ty: &str, reg: &str, label_id: &mut usize) {
    match ty {
        "bool" => alu_bin(out, "AND", reg, "1", reg),
        "u8" => alu_bin(out, "AND", reg, "0x00FF", reg),
        "i8" => {
            alu_bin(out, "AND", reg, "0x00FF", reg);
            mov(out, reg, "R6");
            alu_bin(out, "AND", "R6", "0x0080", "R6");
            alu_cmp(out, "R6", "0");
            let n = *label_id;
            *label_id += 1;
            branch(out, &format!("__cl_tta_norm_{n}"), "CTRL.JZ");
            alu_bin(out, "OR", reg, "0xFF00", reg);
            out.push_str(&format!("__cl_tta_norm_{n}:\n"));
        }
        _ => {}
    }
}

fn emit_startup(out: &mut String, layout: &Layout) {
    out.push_str("; Generated by SVM C-Lite for the TTA16 target.\n");
    out.push_str(".load 0x0100\n.entry __start\n\n.proc __start\n");
    for (name, (_, init)) in &layout.globals {
        let Some(value) = init else { continue };
        mov(out, value.to_string(), "R0");
        store_var(out, &layout.vars[name], "R0");
    }
    branch(out, "main", "CTRL.CALL");
    mov(out, "ZERO", "CTRL.HALT");
    out.push_str(".endproc\n\n");
}

fn emit_compare(
    out: &mut String,
    layout: &Layout,
    function: &str,
    dst: &str,
    op: &str,
    ty: &str,
    left: &str,
    right: &str,
    label_id: &mut usize,
    resident: &mut Resident,
) -> Result<(), String> {
    load_temp(out, layout, function, right, "R1", resident)?;
    load_temp(out, layout, function, left, "R0", resident)?;
    if ty == "i8" {
        alu_bin(out, "XOR", "R0", "0x0080", "R0");
        alu_bin(out, "XOR", "R1", "0x0080", "R1");
    } else if ty == "i16" {
        alu_bin(out, "XOR", "R0", "0x8000", "R0");
        alu_bin(out, "XOR", "R1", "0x8000", "R1");
    }
    alu_cmp(out, "R0", "R1");

    let n = *label_id;
    *label_id += 1;
    let t = format!("__cl_tta_cmp_t_{n}");
    let f = format!("__cl_tta_cmp_f_{n}");
    let e = format!("__cl_tta_cmp_e_{n}");
    match op {
        "eq" => branch(out, &t, "CTRL.JZ"),
        "ne" => branch(out, &t, "CTRL.JNZ"),
        "lt" => branch(out, &t, "CTRL.JNC"),
        "ge" => branch(out, &t, "CTRL.JC"),
        "le" => {
            branch(out, &t, "CTRL.JNC");
            branch(out, &t, "CTRL.JZ");
        }
        "gt" => {
            branch(out, &f, "CTRL.JNC");
            branch(out, &f, "CTRL.JZ");
            branch(out, &t, "CTRL.JMP");
        }
        _ => return Err(format!("bad compare {op}")),
    }
    out.push_str(&format!("{f}:\n"));
    mov(out, "0", "R0");
    branch(out, &e, "CTRL.JMP");
    out.push_str(&format!("{t}:\n"));
    mov(out, "1", "R0");
    out.push_str(&format!("{e}:\n"));
    keep_temp(dst, resident);
    Ok(())
}

fn emit_signed_divmod(
    out: &mut String,
    layout: &Layout,
    function: &str,
    dst: &str,
    op: &str,
    ty: &str,
    left: &str,
    right: &str,
    label_id: &mut usize,
    resident: &mut Resident,
) -> Result<(), String> {
    spill_resident(out, layout, function, resident)?;
    load_temp(out, layout, function, left, "R0", resident)?;
    load_temp(out, layout, function, right, "R1", resident)?;
    normalize(out, ty, "R0", label_id);
    normalize(out, ty, "R1", label_id);
    mov(out, "0", "R2");
    let n = *label_id;
    *label_id += 1;

    alu_cmp(out, "R0", "0");
    branch(out, &format!("__cl_tta_sd_a_{n}"), "CTRL.JNN");
    alu_unary(out, "NEG", "R0", "R0");
    mov(out, "1", "R2");
    out.push_str(&format!("__cl_tta_sd_a_{n}:\n"));
    alu_cmp(out, "R1", "0");
    branch(out, &format!("__cl_tta_sd_b_{n}"), "CTRL.JNN");
    alu_unary(out, "NEG", "R1", "R1");
    if op == "div" {
        alu_bin(out, "XOR", "R2", "1", "R2");
    }
    out.push_str(&format!("__cl_tta_sd_b_{n}:\n"));
    alu_bin(
        out,
        if op == "div" { "DIV" } else { "MOD" },
        "R0",
        "R1",
        "R0",
    );
    alu_cmp(out, "R2", "0");
    branch(out, &format!("__cl_tta_sd_e_{n}"), "CTRL.JZ");
    alu_unary(out, "NEG", "R0", "R0");
    out.push_str(&format!("__cl_tta_sd_e_{n}:\n"));
    normalize(out, ty, "R0", label_id);
    keep_temp(dst, resident);
    Ok(())
}

pub fn lower(clir: &str) -> Result<String, String> {
    let lines = lines(clir);
    let layout = Layout::scan(&lines, true)?;
    let mut out = String::new();
    emit_startup(&mut out, &layout);
    let mut current = String::new();
    let mut label_id = 0usize;
    let mut resident = Resident::default();

    for line in lines {
        if line.starts_with("global ") || line.starts_with("local ") {
            continue;
        }
        if line.starts_with("fn ") {
            let (name, _) = parse_fn_header(line)?;
            current = name.clone();
            resident.clear();
            out.push_str(&format!(".proc {name}\n"));
            continue;
        }
        if line == "end" {
            spill_resident(&mut out, &layout, &current, &mut resident)?;
            out.push_str(".endproc\n\n");
            current.clear();
            continue;
        }
        if line.ends_with(':') {
            spill_resident(&mut out, &layout, &current, &mut resident)?;
            out.push_str(&format!("{}__{}\n", current, line));
            continue;
        }

        if let Some(rest) = line.strip_prefix("const.") {
            let (_, args) = rest.split_once(' ').ok_or("bad const")?;
            let (dst, value) = args.split_once(',').ok_or("bad const")?;
            spill_resident(&mut out, &layout, &current, &mut resident)?;
            mov(&mut out, value.trim(), "R0");
            keep_temp(dst.trim(), &mut resident);
            continue;
        }
        if let Some(rest) = line.strip_prefix("load.") {
            let (ty, args) = rest.split_once(' ').ok_or("bad load")?;
            let (dst, name) = args.split_once(',').ok_or("bad load")?;
            spill_resident(&mut out, &layout, &current, &mut resident)?;
            let var = layout.resolve(&current, name.trim())?;
            load_addr(&mut out, var.addr, "R0", var.width, false);
            normalize(&mut out, ty, "R0", &mut label_id);
            keep_temp(dst.trim(), &mut resident);
            continue;
        }
        if let Some(rest) = line.strip_prefix("store.") {
            let (_, args) = rest.split_once(' ').ok_or("bad store")?;
            let (name, src) = args.split_once(',').ok_or("bad store")?;
            load_temp(&mut out, &layout, &current, src.trim(), "R0", &mut resident)?;
            let var = layout.resolve(&current, name.trim())?;
            store_var(&mut out, &var, "R0");
            continue;
        }
        if let Some(rest) = line.strip_prefix("addr ") {
            let (dst, name) = rest.split_once(',').ok_or("bad addr")?;
            let var = layout.resolve(&current, name.trim())?;
            spill_resident(&mut out, &layout, &current, &mut resident)?;
            mov(&mut out, format!("0x{:04X}", var.addr), "R0");
            keep_temp(dst.trim(), &mut resident);
            continue;
        }
        if let Some(rest) = line.strip_prefix("index ") {
            let p = rest.split(',').map(str::trim).collect::<Vec<_>>();
            if p.len() != 4 {
                return Err("bad index".into());
            }
            if p[3] == "2" {
                load_temp(&mut out, &layout, &current, p[2], "ALU.SHL1", &mut resident)?;
                mov(&mut out, "ALU.OUT", "R1");
            } else {
                load_temp(&mut out, &layout, &current, p[2], "R1", &mut resident)?;
            }
            load_temp(&mut out, &layout, &current, p[1], "ALU.X", &mut resident)?;
            mov(&mut out, "R1", "ALU.ADD");
            mov(&mut out, "ALU.OUT", "R0");
            keep_temp(p[0], &mut resident);
            continue;
        }
        if line.starts_with("loadmem") {
            let volatile = line.starts_with("loadmemv");
            let dot = line.find('.').ok_or("bad loadmem")?;
            let (ty, args) = line[dot + 1..].split_once(' ').ok_or("bad loadmem")?;
            let (dst, address) = args.split_once(',').ok_or("bad loadmem")?;
            let address_port = if volatile { "VMEM.ADDR" } else { "MEM.ADDR" };
            if resident.is(address.trim()) {
                mov(&mut out, "R0", address_port);
                resident.clear();
            } else {
                spill_resident(&mut out, &layout, &current, &mut resident)?;
                load_temp(
                    &mut out,
                    &layout,
                    &current,
                    address.trim(),
                    address_port,
                    &mut resident,
                )?;
            }
            let source = match (volatile, width_of(ty)) {
                (false, 1) => "MEM.R8",
                (false, _) => "MEM.R16",
                (true, 1) => "VMEM.R8",
                (true, _) => "VMEM.R16",
            };
            mov(&mut out, source, "R0");
            normalize(&mut out, ty, "R0", &mut label_id);
            keep_temp(dst.trim(), &mut resident);
            continue;
        }
        if line.starts_with("storemem") {
            let volatile = line.starts_with("storememv");
            let dot = line.find('.').ok_or("bad storemem")?;
            let (ty, args) = line[dot + 1..].split_once(' ').ok_or("bad storemem")?;
            let (address, value) = args.split_once(',').ok_or("bad storemem")?;
            load_temp(
                &mut out,
                &layout,
                &current,
                value.trim(),
                "R0",
                &mut resident,
            )?;
            let address_port = if volatile { "VMEM.ADDR" } else { "MEM.ADDR" };
            load_temp(
                &mut out,
                &layout,
                &current,
                address.trim(),
                address_port,
                &mut resident,
            )?;
            let port = match (volatile, width_of(ty)) {
                (false, 1) => "MEM.W8",
                (false, _) => "MEM.W16",
                (true, 1) => "VMEM.W8",
                (true, _) => "VMEM.W16",
            };
            mov(&mut out, "R0", port);
            continue;
        }
        if let Some(temp) = line.strip_prefix("drop ") {
            if resident.is(temp.trim()) {
                resident.clear();
            }
            continue;
        }
        if let Some(label) = line.strip_prefix("jmp ") {
            spill_resident(&mut out, &layout, &current, &mut resident)?;
            branch(
                &mut out,
                &format!("{current}__{}", label.trim()),
                "CTRL.JMP",
            );
            continue;
        }
        if let Some(rest) = line.strip_prefix("jz ") {
            let (value, label) = rest.split_once(',').ok_or("bad jz")?;
            load_temp(
                &mut out,
                &layout,
                &current,
                value.trim(),
                "R0",
                &mut resident,
            )?;
            alu_cmp(&mut out, "R0", "0");
            branch(&mut out, &format!("{current}__{}", label.trim()), "CTRL.JZ");
            continue;
        }
        if line == "ret" {
            resident.clear();
            mov(&mut out, "CTRL.RETADDR", "CTRL.JMP");
            continue;
        }
        if let Some(value) = line.strip_prefix("ret ") {
            load_temp(
                &mut out,
                &layout,
                &current,
                value.trim(),
                "R0",
                &mut resident,
            )?;
            mov(&mut out, "CTRL.RETADDR", "CTRL.JMP");
            continue;
        }
        if line.starts_with("call") {
            spill_resident(&mut out, &layout, &current, &mut resident)?;
            let (dst, name, args) = parse_call(line)?;
            let function = layout
                .funcs
                .get(name)
                .ok_or_else(|| format!("unknown call target {name}"))?;
            if args.len() != function.params.len() {
                return Err(format!("call arity mismatch for {name}"));
            }
            for (arg, (param, _)) in args.iter().zip(&function.params) {
                load_temp(&mut out, &layout, &current, arg, "R0", &mut resident)?;
                let slot = layout.resolve(name, param)?;
                store_var(&mut out, &slot, "R0");
            }
            branch(&mut out, name, "CTRL.CALL");
            resident.clear();
            if let Some(dst) = dst {
                keep_temp(dst, &mut resident);
            }
            continue;
        }

        if let Some((op_ty, args)) = line.split_once(' ') {
            if let Some((op, ty)) = op_ty.split_once('.') {
                if matches!(op, "neg" | "not") {
                    let (dst, src) = args.split_once(',').ok_or("bad unary")?;
                    let port = if op == "neg" { "ALU.NEG" } else { "ALU.NOT" };
                    load_temp(&mut out, &layout, &current, src.trim(), port, &mut resident)?;
                    mov(&mut out, "ALU.OUT", "R0");
                    normalize(&mut out, ty, "R0", &mut label_id);
                    keep_temp(dst.trim(), &mut resident);
                    continue;
                }
                let p = args.split(',').map(str::trim).collect::<Vec<_>>();
                if p.len() != 3 {
                    return Err(format!("bad binary CLIR: {line}"));
                }
                if matches!(op, "eq" | "ne" | "lt" | "le" | "gt" | "ge") {
                    emit_compare(
                        &mut out,
                        &layout,
                        &current,
                        p[0],
                        op,
                        ty,
                        p[1],
                        p[2],
                        &mut label_id,
                        &mut resident,
                    )?;
                } else if matches!(op, "div" | "mod") && matches!(ty, "i8" | "i16") {
                    emit_signed_divmod(
                        &mut out,
                        &layout,
                        &current,
                        p[0],
                        op,
                        ty,
                        p[1],
                        p[2],
                        &mut label_id,
                        &mut resident,
                    )?;
                } else {
                    let alu = match op {
                        "add" => "ADD",
                        "sub" => "SUB",
                        "mul" => "MUL",
                        "div" => "DIV",
                        "mod" => "MOD",
                        "and" => "AND",
                        "or" => "OR",
                        "xor" => "XOR",
                        "shl" => "SHL",
                        "shr" => "SHR",
                        _ => return Err(format!("unsupported TTA CLIR op {op}")),
                    };
                    load_temp(
                        &mut out,
                        &layout,
                        &current,
                        p[2],
                        &format!("ALU.{alu}"),
                        &mut resident,
                    )?;
                    load_temp(&mut out, &layout, &current, p[1], "ALU.X", &mut resident)?;
                    mov(&mut out, "ALU.OUT", "R0");
                    normalize(&mut out, ty, "R0", &mut label_id);
                    keep_temp(p[0], &mut resident);
                }
                continue;
            }
        }
        return Err(format!("unsupported TTA CLIR line: {line}"));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lowers_clir_to_transports() {
        let clir = "fn main() -> u16\n  const.u16 %0, 7\n  const.u16 %1, 5\n  mul.u16 %2, %0, %1\n  ret %2\nend\n";
        let asm = lower(clir).unwrap();
        assert!(asm.contains("ALU.MUL"));
        assert!(asm.contains("CTRL.RETADDR,CTRL.JMP"));

        let temp_spills = asm
            .lines()
            .filter(|line| line.trim_end().ends_with(",MEM.W16"))
            .count();
        assert_eq!(temp_spills, 1, "only the displaced first temp should spill");
        assert!(
            !asm.contains(",R7"),
            "static temp access should address MEM directly"
        );
    }

    #[test]
    fn compare_uses_flags_without_copying_alu_out() {
        let clir = "fn main() -> u16\n  const.u16 %0, 1\n  const.u16 %1, 2\n  lt.u16 %2, %0, %1\n  ret %2\nend\n";
        let asm = lower(clir).unwrap();
        assert!(asm.contains("ALU.CMP"));
        assert!(!asm.contains("ALU.OUT,R6"));
    }
}
